// nesppu — the Famicom's picture processing unit (RP2C02).
//
// The PPU is not a frame buffer. It is a machine that walks a fixed raster —
// 341 dots x 262 scanlines, three dots per CPU cycle — fetching tiles just
// ahead of the beam. Everything that looks like a "trick" on this console is
// a game exploiting *where the beam is*: split-screen status bars, parallax
// scrolls, mid-frame palette changes. So this core is ticked per dot, and the
// machine ticks it from inside the CPU's bus accesses. That gives register
// writes their exact position on the raster for free, which is the only way
// sprite 0 hit and MMC3's scanline IRQ can be right.
//
// The scroll registers deserve the same treatment. The PPU does not have an
// "X scroll" and a "Y scroll"; it has two 15-bit address registers (v and t),
// a 3-bit fine-X (x) and a write toggle (w). $2005 and $2006 both write into
// the same t, in overlapping bit fields, and v is *also* the VRAM address
// used by $2007. Model those four and scrolling comes out correct, including
// the cases that look like bugs — the mid-frame $2006 write that moves the
// screen, the $2005/$2006 sequence every scrolling game uses. Model "scrollX
// / scrollY" instead and you spend forever special-casing games. This file
// uses loopy's v/t/x/w names deliberately: the register-level docs everyone
// cites use them, so the code and the documentation stay readable together.
//
// Output is plain data: `frameBuf` holds one NES palette index (0..63) per
// pixel and `frameEmph` the colour-emphasis bits in force when that pixel was
// drawn. No DOM, no RGB decisions — the machine turns those into pixels, the
// way machine88.js turns the 8801's palette indices into pixels.
//
// Suite contract: pure, dependency-free, deterministic, no Math.random.
// getState()/setState() are exact inverses. The frame buffers are NOT part of
// the state: they are regenerated by the next frame, and snapshots are taken
// at frame boundaries (see docs/nes-design.md §5).

// snap.js is this repository's snapshot plumbing (pure, dependency-free, no
// sibling engine behind it) — the same helpers the PC Engine packs its picture
// with, so the two consoles cannot drift apart on what a snapshot owes the host.
import { packPixels, unpackPixels, rlePlane, unrlePlane } from './snap.js';

export const SCHEMA_VERSION = 1;

export const SCREEN_W = 256;
export const SCREEN_H = 240;
export const DOTS_PER_LINE = 341;
export const LINES_PER_FRAME = 262;
export const PRERENDER_LINE = 261;
export const VBLANK_LINE = 241;

// The 2C02's 64 colours, as the composite signal decodes on a normal NTSC
// set. There is no "correct" table — the chip generates colour by phase, not
// by a ROM — but this is the one most emulators and most screenshots agree on.
export const NES_PALETTE = Uint32Array.from([
  0x666666, 0x002a88, 0x1412a7, 0x3b00a4, 0x5c007e, 0x6e0040, 0x6c0600, 0x561d00,
  0x333500, 0x0b4800, 0x005200, 0x004f08, 0x00404d, 0x000000, 0x000000, 0x000000,
  0xadadad, 0x155fd9, 0x4240ff, 0x7527fe, 0xa01acc, 0xb71e7b, 0xb53120, 0x994e00,
  0x6b6d00, 0x388700, 0x0c9300, 0x008f32, 0x007c8d, 0x000000, 0x000000, 0x000000,
  0xfffeff, 0x64b0ff, 0x9290ff, 0xc676ff, 0xf36aff, 0xfe6ecc, 0xfe8170, 0xea9e22,
  0xbcbe00, 0x88d800, 0x5ce430, 0x45e082, 0x48cdde, 0x4f4f4f, 0x000000, 0x000000,
  0xfffeff, 0xc0dfff, 0xd3d2ff, 0xe8c8ff, 0xfbc2ff, 0xfec4ea, 0xfeccc5, 0xf7d8a5,
  0xe4e594, 0xcfef96, 0xbdf4ab, 0xb3f3cc, 0xb5ebf2, 0xb8b8b8, 0x000000, 0x000000,
]);

// Colour emphasis ($2001 bits 5-7) is an analogue effect: setting a bit boosts
// that primary by pulling the OTHER two down. All three set therefore dims the
// whole picture, which is exactly what games use it for (the damage flash in
// Mega Man, the "screen goes dark" transitions). 0.746 is the attenuation the
// hardware measurements settle on.
const EMPH_ATTEN = 0.746;

// A flat LUT: index = (emphasis << 6) | colour, 3 bytes per entry. Built once;
// the machine's render() is then a table lookup per pixel.
export function buildNesPaletteRgb() {
  const out = new Uint8Array(64 * 8 * 3);
  for (let e = 0; e < 8; e++) {
    const dimR = (e & 2) || (e & 4) ? EMPH_ATTEN : 1; // green or blue emphasis dims red
    const dimG = (e & 1) || (e & 4) ? EMPH_ATTEN : 1;
    const dimB = (e & 1) || (e & 2) ? EMPH_ATTEN : 1;
    for (let c = 0; c < 64; c++) {
      const rgb = NES_PALETTE[c];
      const o = ((e << 6) | c) * 3;
      out[o] = Math.min(255, Math.round(((rgb >> 16) & 0xff) * dimR));
      out[o + 1] = Math.min(255, Math.round(((rgb >> 8) & 0xff) * dimG));
      out[o + 2] = Math.min(255, Math.round((rgb & 0xff) * dimB));
    }
  }
  return out;
}

export class NesPpu {
  // `mapper` supplies CHR ($0000-$1FFF) and the nametable wiring; the PPU owns
  // CIRAM (the console's own 2KB, or 4KB on a four-screen board) and the
  // palette. That split follows the hardware: the console never learns what
  // board is plugged in, it just drives the address bus.
  constructor(mapper, { fourScreen = false } = {}) {
    this.mapper = mapper;
    this.ciram = new Uint8Array(fourScreen ? 4096 : 2048);
    this.paletteRam = new Uint8Array(32);
    this.oam = new Uint8Array(256);
    this.secOam = new Uint8Array(32);
    this.frameBuf = new Uint8Array(SCREEN_W * SCREEN_H);
    this.frameEmph = new Uint8Array(SCREEN_W * SCREEN_H);
    // Sprite output units: eight of everything, latched during dots 257-320
    // of the PREVIOUS scanline. Separate arrays rather than objects so the
    // per-pixel loop stays free of property lookups.
    this.spPatLo = new Uint8Array(8);
    this.spPatHi = new Uint8Array(8);
    this.spAttr = new Uint8Array(8);
    this.spX = new Uint8Array(8);
    this.powerOn();
  }

  powerOn() {
    this.ctrl = 0; this.mask = 0; this.status = 0;
    this.oamAddr = 0;
    this.v = 0; this.t = 0; this.x = 0; this.w = 0;
    this.readBuffer = 0;
    this.openBus = 0;
    this.rendering = false;
    this.scanline = PRERENDER_LINE; this.dot = 340; // first tick() lands on (0,0)
    this.oddFrame = false; this.skipDot = false;
    this.frameComplete = false;
    this.nmiOccurred = false;
    this.suppressVbl = false;
    this.busAddr = 0; this.busPrev = 0;
    // background pipeline
    this.ntByte = 0; this.atByte = 0; this.bgLo = 0; this.bgHi = 0;
    this.bgShiftLo = 0; this.bgShiftHi = 0; this.atShiftLo = 0; this.atShiftHi = 0;
    // sprite evaluation
    this.oamN = 0; this.oamM = 0; this.oamLatch = 0;
    this.secCount = 0; this.evalState = 0; this.ovCopy = 0;
    this.sprZeroNext = false; this.sprZeroLine = false; this.sprCount = 0;
    this.ciram.fill(0); this.oam.fill(0); this.secOam.fill(0xff);
    // Power-on palette is not zero on real hardware, but it is undefined; zero
    // is the only choice that keeps two fresh machines bit-identical.
    this.paletteRam.fill(0);
    this.frameBuf.fill(0); this.frameEmph.fill(0);
    return this;
  }

  reset() {
    // RESET clears the control/mask registers and the write toggle; VRAM and
    // OAM survive (which is why a reset mid-game keeps the graphics).
    this.ctrl = 0; this.mask = 0; this.rendering = false;
    this.w = 0; this.readBuffer = 0;
    this.scanline = PRERENDER_LINE; this.dot = 340;
    this.oddFrame = false; this.frameComplete = false; this.skipDot = false;
    return this;
  }

  // ---- PPU memory ----------------------------------------------------------
  // Every fetch goes through here so the mapper sees the address bus; MMC3's
  // scanline counter is nothing but a watcher on address line A12.
  _read(addr) {
    addr &= 0x3fff;
    this.busAddr = addr;
    if (addr < 0x2000) return this.mapper.ppuRead(addr);
    if (addr < 0x3f00) return this.ciram[this._ntIndex(addr)];
    return this.paletteRam[palIdx(addr)];
  }

  _write(addr, value) {
    addr &= 0x3fff;
    this.busAddr = addr;
    if (addr < 0x2000) { this.mapper.ppuWrite(addr, value); return; }
    if (addr < 0x3f00) { this.ciram[this._ntIndex(addr)] = value; return; }
    // Only the low 6 bits exist in palette RAM; the top two read back as
    // whatever was on the bus, which is why $FF writes read back as $3F.
    this.paletteRam[palIdx(addr)] = value & 0x3f;
  }

  // Four nametable addresses, two (or four) real kilobytes. Which pairs share
  // memory is a property of the BOARD, and MMC1/MMC3 change it at run time,
  // so we ask the mapper every fetch rather than caching it.
  _ntIndex(addr) {
    const nt = (addr >> 10) & 3;
    const off = addr & 0x3ff;
    switch (this.mapper.mirroring) {
      case 1: return ((nt & 1) << 10) | off;        // vertical
      case 2: return off;                           // single-screen A
      case 3: return 0x400 | off;                   // single-screen B
      case 4: return ((nt << 10) | off) & (this.ciram.length - 1); // four-screen
      default: return ((nt >> 1) << 10) | off;      // horizontal
    }
  }

  // ---- CPU-visible registers ($2000-$2007) --------------------------------
  readReg(reg) {
    switch (reg & 7) {
      case 2: {
        // The vblank flag and its race. Reading $2002 clears the flag AND the
        // NMI condition, so a read landing on the exact dot the flag is set
        // makes the NMI never happen. Games poll $2002 in a tight loop, so
        // this is not a corner case: it is the difference between a game
        // running and a game freezing every few minutes.
        if (this.scanline === VBLANK_LINE && this.dot === 0) this.suppressVbl = true;
        const v = (this.status & 0xe0) | (this.openBus & 0x1f);
        this.status &= ~0x80;
        this.nmiOccurred = false;
        this.w = 0; // reading $2002 resets the $2005/$2006 write toggle
        this.openBus = v;
        return v;
      }
      case 4: {
        // During the first 64 dots of a rendering scanline the chip is
        // clearing secondary OAM and $2004 reads back $FF.
        let v;
        if (this.rendering && (this.scanline < 240 || this.scanline === PRERENDER_LINE) && this.dot >= 1 && this.dot <= 64) v = 0xff;
        else v = this.oam[this.oamAddr];
        // Sprite attribute bytes have three unimplemented bits that read 0.
        if ((this.oamAddr & 3) === 2) v &= 0xe3;
        this.openBus = v;
        return v;
      }
      case 7: {
        const addr = this.v & 0x3fff;
        let v;
        if (addr >= 0x3f00) {
          // Palette reads are immediate, but the read-ahead buffer is still
          // filled — with the nametable byte "underneath" the palette mirror.
          v = this.paletteRam[palIdx(addr)] & (this.mask & 1 ? 0x30 : 0x3f);
          v |= this.openBus & 0xc0;
          this.readBuffer = this.ciram[this._ntIndex(addr & 0x2fff)];
        } else {
          v = this.readBuffer;
          this.readBuffer = this._read(addr);
        }
        this._incVram();
        this.openBus = v;
        return v;
      }
      default:
        // Write-only registers return the PPU's open bus (the last value that
        // travelled the CPU<->PPU data bus).
        return this.openBus;
    }
  }

  writeReg(reg, value) {
    value &= 0xff;
    this.openBus = value;
    switch (reg & 7) {
      case 0: {
        const wasNmi = (this.ctrl & 0x80) !== 0;
        this.ctrl = value;
        // t: ....GH.. ........ <- d: ......GH  (nametable select)
        this.t = (this.t & 0x73ff) | ((value & 3) << 10);
        // Turning NMI-on-vblank on WHILE the vblank flag is already set fires
        // an NMI immediately. Games use it to defer the handler; nmiLine()
        // reports the level, so the machine picks the edge up on its own.
        if (!wasNmi && (value & 0x80) && this.nmiOccurred) { /* level goes high */ }
        break;
      }
      case 1:
        this.mask = value;
        this.rendering = (value & 0x18) !== 0;
        break;
      case 3:
        this.oamAddr = value;
        break;
      case 4:
        // Writes during rendering are corrupt on hardware; games do not do it,
        // and the honest simple behaviour (ignore the increment) is closer than
        // performing a clean write.
        if (this.rendering && (this.scanline < 240 || this.scanline === PRERENDER_LINE)) {
          this.oamAddr = (this.oamAddr + 4) & 0xff;
          break;
        }
        this.oam[this.oamAddr] = value;
        this.oamAddr = (this.oamAddr + 1) & 0xff;
        break;
      case 5:
        if (this.w === 0) {
          // t: ....... ...ABCDE <- d: ABCDE...   x: FGH
          this.t = (this.t & 0x7fe0) | (value >> 3);
          this.x = value & 7;
          this.w = 1;
        } else {
          // t: FGH..AB CDE..... <- d: ABCDEFGH
          this.t = (this.t & 0x0c1f) | ((value & 7) << 12) | ((value & 0xf8) << 2);
          this.w = 0;
        }
        break;
      case 6:
        if (this.w === 0) {
          // t: .CDEFGH ........ <- d: ..CDEFGH  (bit 14 is cleared: the
          // address space is 14 bits, so a write here always lands in it)
          this.t = (this.t & 0x00ff) | ((value & 0x3f) << 8);
          this.w = 1;
        } else {
          this.t = (this.t & 0x7f00) | value;
          this.v = this.t;
          this._busIdle();
          this.w = 0;
        }
        break;
      case 7:
        this._write(this.v & 0x3fff, value);
        this._incVram();
        break;
      default:
        break;
    }
  }

  _incVram() {
    this.v = (this.v + ((this.ctrl & 4) ? 32 : 1)) & 0x7fff;
    this._busIdle();
  }

  // With rendering off, the PPU address bus simply holds v — which is how a
  // game can clock MMC3's counter by writing $2006 twice, with no picture at
  // all. Keep the mapper informed of that too.
  _busIdle() {
    if (!this.rendering) {
      this.busAddr = this.v & 0x3fff;
      if (this.mapper.wantsPpuBus) this.mapper.ppuAddrBus(this.busAddr, 1);
    }
  }

  // The NMI line as the CPU sees it (active = true). Level, not edge: the
  // machine feeds it to the CPU every cycle and the CPU's own edge detector
  // decides. That is what makes "$2000 written while vblank is set" fire.
  nmiLine() { return this.nmiOccurred && (this.ctrl & 0x80) !== 0; }

  // ---- the raster ----------------------------------------------------------
  tick() {
    this._advance();
    const sl = this.scanline, dot = this.dot;

    if (sl === VBLANK_LINE && dot === 1) {
      if (!this.suppressVbl) { this.status |= 0x80; this.nmiOccurred = true; }
      this.suppressVbl = false;
      this.frameComplete = true;
    }
    if (sl === PRERENDER_LINE && dot === 1) {
      this.status &= ~0xe0; // vblank + sprite 0 hit + sprite overflow
      this.nmiOccurred = false;
    }
    // Whether the odd-frame dot is skipped is decided at dot 339, not at 340:
    // a game that switches the background on during the pre-render line finds
    // the decision already made. blargg's 10-even_odd_timing measures exactly
    // this, and latching one dot later fails it.
    if (sl === PRERENDER_LINE && dot === 339) this.skipDot = this.rendering;

    const visible = sl < 240;
    const active = visible || sl === PRERENDER_LINE;

    if (active && this.rendering) {
      this._bgTick(sl, dot);
      this._spriteTick(sl, dot);
    } else {
      // Rendering off (or off-screen): the address bus just holds v. This is
      // not a detail — it is how a game with the picture disabled still
      // clocks MMC3's counter by writing $2006, and the A12-low time here is
      // what arms the filter for the next real fetch.
      this.busAddr = this.v & 0x3fff;
    }
    // One dot of lag, deliberately. The PPU drives an address during a dot and
    // the board only sees it settle on the next one. mmc3_test's
    // 4-scanline_timing measures the resulting IRQ position to a single PPU
    // clock, and without this lag every A12 rise — and so every scanline IRQ —
    // lands one dot early, in both the $2000=$08 and the $2000=$10 layout.
    if (this.mapper.wantsPpuBus) this.mapper.ppuAddrBus(this.busPrev, 1);
    this.busPrev = this.busAddr;

    // Visible dots always produce a pixel: with rendering disabled that is the
    // backdrop colour, which is what a real set shows during a screen-off
    // transition (and what _pixel returns when both mask bits are clear).
    if (visible && dot >= 1 && dot <= 256) this._pixel(sl, dot - 1);
  }

  _advance() {
    this.dot++;
    // The odd-frame short line: with rendering on, the last dot of the
    // pre-render scanline is skipped every other frame. That one dot is what
    // keeps the colour burst in phase — and it is also why a frame is not a
    // constant number of cycles, which any "cycles per frame" emulator gets
    // subtly wrong.
    if (this.dot === 340 && this.scanline === PRERENDER_LINE && this.oddFrame && this.skipDot) this.dot = 341;
    if (this.dot > 340) {
      this.dot = 0;
      this.scanline++;
      if (this.scanline > PRERENDER_LINE) { this.scanline = 0; this.oddFrame = !this.oddFrame; }
    }
  }

  // ---- background ----------------------------------------------------------
  _bgTick(sl, dot) {
    if ((dot >= 2 && dot <= 257) || (dot >= 322 && dot <= 337)) this._shift();

    if ((dot >= 1 && dot <= 256) || (dot >= 321 && dot <= 336)) {
      switch ((dot - 1) & 7) {
        case 0:
          this._reload();
          this.ntByte = this._read(0x2000 | (this.v & 0x0fff));
          break;
        case 2: {
          // The attribute byte covers a 32x32 pixel area in four 2-bit
          // fields; which field applies is bit 1 of coarse X and coarse Y.
          const at = this._read(0x23c0 | (this.v & 0x0c00) | ((this.v >> 4) & 0x38) | ((this.v >> 2) & 0x07));
          let q = at;
          if (this.v & 0x40) q >>= 4;   // coarse Y bit 1
          if (this.v & 0x02) q >>= 2;   // coarse X bit 1
          this.atByte = q & 3;
          break;
        }
        case 4:
          this.bgLo = this._read(((this.ctrl & 0x10) << 8) | (this.ntByte << 4) | ((this.v >> 12) & 7));
          break;
        case 6:
          this.bgHi = this._read(((this.ctrl & 0x10) << 8) | (this.ntByte << 4) | ((this.v >> 12) & 7) | 8);
          break;
        case 7:
          this._incCoarseX();
          break;
        default:
          break;
      }
    }

    if (dot === 256) this._incY();
    if (dot === 257) { this._reload(); this.v = (this.v & ~0x041f) | (this.t & 0x041f); } // copy horizontal
    if (sl === PRERENDER_LINE && dot >= 280 && dot <= 304) this.v = (this.v & ~0x7be0) | (this.t & 0x7be0); // copy vertical
    // Two more nametable fetches at the end of the line. They fetch nothing
    // useful — but they DO put $2xxx on the address bus, which is part of the
    // A12 pattern MMC3 counts, so they are not optional.
    if (dot === 339 || dot === 337) this._read(0x2000 | (this.v & 0x0fff));
  }

  _shift() {
    this.bgShiftLo = (this.bgShiftLo << 1) & 0xffff;
    this.bgShiftHi = (this.bgShiftHi << 1) & 0xffff;
    this.atShiftLo = (this.atShiftLo << 1) & 0xffff;
    this.atShiftHi = (this.atShiftHi << 1) & 0xffff;
  }

  _reload() {
    this.bgShiftLo = (this.bgShiftLo & 0xff00) | this.bgLo;
    this.bgShiftHi = (this.bgShiftHi & 0xff00) | this.bgHi;
    // The attribute bits are 2 bits per TILE but have to line up with 8 pixels,
    // so they are smeared into the same shift registers as $00 or $FF.
    this.atShiftLo = (this.atShiftLo & 0xff00) | ((this.atByte & 1) ? 0xff : 0);
    this.atShiftHi = (this.atShiftHi & 0xff00) | ((this.atByte & 2) ? 0xff : 0);
  }

  // Coarse X lives in v bits 0-4 and wraps into the horizontal nametable bit.
  _incCoarseX() {
    if ((this.v & 0x001f) === 31) this.v = (this.v & ~0x001f) ^ 0x0400;
    else this.v++;
  }

  // Fine Y (bits 12-14) then coarse Y (bits 5-9), which wraps at 29 — not 31 —
  // because rows 30 and 31 are the attribute table. A game that sets coarse Y
  // to 30 gets the attribute bytes rendered as tiles, and real games do it on
  // purpose; that is why the 30/31 case is handled separately.
  _incY() {
    if ((this.v & 0x7000) !== 0x7000) { this.v += 0x1000; return; }
    this.v &= ~0x7000;
    let y = (this.v & 0x03e0) >> 5;
    if (y === 29) { y = 0; this.v ^= 0x0800; }
    else if (y === 31) y = 0;
    else y++;
    this.v = (this.v & ~0x03e0) | (y << 5);
  }

  // ---- sprites -------------------------------------------------------------
  _spriteTick(sl, dot) {
    // Evaluation runs on the line BEFORE the sprites appear, which is why a
    // sprite at Y=0 shows up on scanline 1 and nothing is ever drawn on
    // scanline 0. Modelling the pre-render line as -1 gets that for free.
    const evalLine = sl === PRERENDER_LINE ? -1 : sl;
    if (dot >= 1 && dot <= 256) this._evalSprites(evalLine, dot);
    if (dot >= 257 && dot <= 320) {
      this.oamAddr = 0; // hardware forces it to zero for this whole window
      this._fetchSprites(evalLine, dot);
    }
  }

  _evalSprites(sl, dot) {
    if (dot <= 64) {
      // Secondary OAM clear: $FF written on the even dots.
      if ((dot & 1) === 0) this.secOam[(dot >> 1) - 1] = 0xff;
      return;
    }
    if (dot === 65) {
      this.oamN = 0; this.oamM = 0; this.secCount = 0;
      this.evalState = 0; this.ovCopy = 0; this.sprZeroNext = false;
    }
    if (dot & 1) {
      // Odd dots read OAM. Evaluation starts at OAMADDR, not at 0 — a game
      // that leaves OAMADDR non-zero at the end of vblank gets its sprite
      // list rotated, and a couple of games rely on exactly that.
      this.oamLatch = this.oam[(this.oamAddr + this.oamN * 4 + this.oamM) & 0xff];
      return;
    }

    const height = (this.ctrl & 0x20) ? 16 : 8;
    switch (this.evalState) {
      case 0: { // looking for in-range sprites, room left in secondary OAM
        if (this.secCount < 8) this.secOam[this.secCount * 4 + this.oamM] = this.oamLatch;
        if (this.oamM === 0) {
          const d = sl - this.oamLatch;
          if (d >= 0 && d < height) {
            if (this.oamN === 0) this.sprZeroNext = true;
            this.oamM = 1;
          } else {
            if (++this.oamN >= 64) { this.oamN = 0; this.evalState = 2; }
          }
        } else if (++this.oamM === 4) {
          this.oamM = 0;
          this.secCount++;
          if (++this.oamN >= 64) { this.oamN = 0; this.evalState = 2; }
          else if (this.secCount === 8) this.evalState = 1;
        }
        break;
      }
      case 1: { // eight found; keep scanning only to decide the overflow flag
        const d = sl - this.oamLatch;
        if (d >= 0 && d < height) {
          this.status |= 0x20;
          this.evalState = 3; this.ovCopy = 3;
        } else {
          // THE sprite overflow bug: hardware increments n AND m here, so it
          // starts reading the Y coordinate from the wrong byte of the next
          // sprite. The flag therefore fires on lines with fewer than nine
          // sprites and misses lines with more. Games that use it as a raster
          // timer were written against the buggy behaviour, so reproducing
          // the bug is not pedantry — a "corrected" version breaks them.
          if (++this.oamN >= 64) { this.oamN = 0; this.evalState = 2; }
          this.oamM = (this.oamM + 1) & 3;
        }
        break;
      }
      case 3: { // overflow found: three more reads before evaluation stops
        if (++this.oamM === 4) { this.oamM = 0; if (++this.oamN >= 64) this.oamN = 0; }
        if (--this.ovCopy === 0) this.evalState = 2;
        break;
      }
      default: // 2 = finished for this line; reads continue, nothing changes
        break;
    }
  }

  _fetchSprites(sl, dot) {
    const i = (dot - 257) >> 3;
    const phase = (dot - 257) & 7;
    if (phase === 0) {
      if (i === 0) { this.sprCount = this.secCount; this.sprZeroLine = this.sprZeroNext; }
      this.spAttr[i] = this.secOam[i * 4 + 2];
      this.spX[i] = this.secOam[i * 4 + 3];
    }
    // Garbage nametable/attribute fetches. They exist only to keep the bus
    // busy, but they hold $2xxx (A12 low) for four dots, which is half of
    // MMC3's filter window — drop them and the scanline counter runs wild.
    if (phase === 0 || phase === 2) { this._read(0x2000 | (this.v & 0x0fff)); return; }
    if (phase !== 4 && phase !== 6) return;

    const height = (this.ctrl & 0x20) ? 16 : 8;
    const y = this.secOam[i * 4];
    const tile = this.secOam[i * 4 + 1];
    const attr = this.secOam[i * 4 + 2];
    // Slots past the last found sprite still fetch — tile $FF, row 0 — and
    // that dummy fetch is visible on the address bus.
    const used = i < this.secCount;
    let row = used ? sl - y : 0;
    if (row < 0 || row >= height) row = 0;
    if (used && (attr & 0x80)) row = height - 1 - row;

    let addr;
    if (height === 16) {
      // 8x16 sprites pick their pattern table from the tile number's bit 0,
      // and the bottom half is the next tile — hence the (row & 8) << 1.
      addr = ((tile & 1) << 12) | ((tile & 0xfe) << 4) | ((row & 8) << 1) | (row & 7);
    } else {
      addr = ((this.ctrl & 0x08) << 9) | (tile << 4) | (row & 7);
    }
    if (phase === 4) {
      const b = this._read(addr);
      this.spPatLo[i] = used ? (attr & 0x40 ? reverseByte(b) : b) : 0;
    } else {
      const b = this._read(addr | 8);
      this.spPatHi[i] = used ? (attr & 0x40 ? reverseByte(b) : b) : 0;
    }
  }

  // ---- one pixel -----------------------------------------------------------
  _pixel(sl, px) {
    let bg = 0, bgPal = 0;
    if ((this.mask & 0x08) && (px >= 8 || (this.mask & 0x02))) {
      const bit = 0x8000 >> this.x;
      bg = ((this.bgShiftLo & bit) ? 1 : 0) | ((this.bgShiftHi & bit) ? 2 : 0);
      if (bg) bgPal = ((this.atShiftLo & bit) ? 1 : 0) | ((this.atShiftHi & bit) ? 2 : 0);
    }

    let sp = 0, spPal = 0, spPriority = 0, spIsZero = false;
    if ((this.mask & 0x10) && (px >= 8 || (this.mask & 0x04))) {
      for (let i = 0; i < this.sprCount; i++) {
        const off = px - this.spX[i];
        if (off < 0 || off > 7) continue;
        const bit = 0x80 >> off;
        const c = ((this.spPatLo[i] & bit) ? 1 : 0) | ((this.spPatHi[i] & bit) ? 2 : 0);
        if (!c) continue; // transparent: a lower-priority sprite can still show
        sp = c;
        spPal = this.spAttr[i] & 3;
        spPriority = this.spAttr[i] & 0x20;
        spIsZero = i === 0 && this.sprZeroLine;
        break; // first (lowest OAM index) opaque sprite wins
      }
    }

    // Sprite 0 hit: the flag a game polls to find out where the beam is, and
    // the reason split-screen scrolling exists at all. Not set on the last
    // pixel of the line (a hardware quirk), and not while either layer is
    // clipped at the left edge.
    if (spIsZero && bg && sp && px !== 255) this.status |= 0x40;

    let idx;
    if (sp && (!bg || !spPriority)) idx = 0x10 | (spPal << 2) | sp;
    else if (bg) idx = (bgPal << 2) | bg;
    else idx = 0;
    let colour = this.paletteRam[palIdx(0x3f00 | idx)];
    if (this.mask & 1) colour &= 0x30; // greyscale: keep only the luma column

    const o = sl * SCREEN_W + px;
    this.frameBuf[o] = colour & 0x3f;
    this.frameEmph[o] = (this.mask >> 5) & 7;
  }

  // ---- state ---------------------------------------------------------------
  // The frame buffers used to be deliberately absent — "output, regenerated by
  // the next frame, and 120KB per snapshot would cut the rewind window by an
  // order of magnitude for nothing". Every word of that is true and the
  // conclusion was still wrong: nothing steps a frame before showing the
  // picture. demo/machine.html's restoreIdx() restores and draws, so a snapshot
  // without a picture shows whatever was on screen when the user scrubbed, and
  // every slot of the 120-frame rewind ring comes back as the newest frame.
  // The Game Boy found this on 2026-08-10 (see docs/gb-design.md §12); this PPU
  // had it for the same reason, written down in the same words.
  //
  // The size objection is answered by packing rather than by omitting: the
  // palette index is six bits, so 61,440 pixels are 46,080 bytes, and the three
  // emphasis bits are constant for a whole frame in everything that is not
  // doing a mid-screen $2001 write, so they go in as runs (typically 4 bytes).
  // ~46KB per snapshot against ~3KB of the rest — the ring is the thing that
  // has to be sized for it, and a ring of wrong pictures is worth nothing.
  getState() {
    return {
      schemaVersion: SCHEMA_VERSION,
      frameBuf: packPixels(this.frameBuf, 6),
      frameEmph: rlePlane(this.frameEmph),
      ciram: this.ciram.slice(),
      paletteRam: this.paletteRam.slice(),
      oam: this.oam.slice(),
      secOam: this.secOam.slice(),
      spPatLo: this.spPatLo.slice(), spPatHi: this.spPatHi.slice(),
      spAttr: this.spAttr.slice(), spX: this.spX.slice(),
      ctrl: this.ctrl, mask: this.mask, status: this.status, oamAddr: this.oamAddr,
      v: this.v, t: this.t, x: this.x, w: this.w,
      readBuffer: this.readBuffer, openBus: this.openBus,
      scanline: this.scanline, dot: this.dot, oddFrame: this.oddFrame, skipDot: this.skipDot,
      frameComplete: this.frameComplete, nmiOccurred: this.nmiOccurred,
      suppressVbl: this.suppressVbl, busAddr: this.busAddr, busPrev: this.busPrev,
      ntByte: this.ntByte, atByte: this.atByte, bgLo: this.bgLo, bgHi: this.bgHi,
      bgShiftLo: this.bgShiftLo, bgShiftHi: this.bgShiftHi,
      atShiftLo: this.atShiftLo, atShiftHi: this.atShiftHi,
      oamN: this.oamN, oamM: this.oamM, oamLatch: this.oamLatch,
      secCount: this.secCount, evalState: this.evalState, ovCopy: this.ovCopy,
      sprZeroNext: this.sprZeroNext, sprZeroLine: this.sprZeroLine, sprCount: this.sprCount,
    };
  }

  setState(s) {
    // A snapshot from before the picture went in restores a black screen
    // rather than silently keeping the last one drawn — the failure this
    // whole field exists to prevent.
    if (s.frameBuf) unpackPixels(s.frameBuf, 6, SCREEN_W * SCREEN_H, this.frameBuf);
    else this.frameBuf.fill(0);
    if (s.frameEmph) unrlePlane(s.frameEmph, SCREEN_W * SCREEN_H, this.frameEmph);
    else this.frameEmph.fill(0);
    this.ciram.set(s.ciram);
    this.paletteRam.set(s.paletteRam);
    this.oam.set(s.oam);
    this.secOam.set(s.secOam);
    this.spPatLo.set(s.spPatLo); this.spPatHi.set(s.spPatHi);
    this.spAttr.set(s.spAttr); this.spX.set(s.spX);
    this.ctrl = s.ctrl; this.mask = s.mask; this.status = s.status; this.oamAddr = s.oamAddr;
    this.rendering = (this.mask & 0x18) !== 0;
    this.v = s.v; this.t = s.t; this.x = s.x; this.w = s.w;
    this.readBuffer = s.readBuffer; this.openBus = s.openBus;
    this.scanline = s.scanline; this.dot = s.dot; this.oddFrame = s.oddFrame; this.skipDot = !!s.skipDot;
    this.frameComplete = s.frameComplete; this.nmiOccurred = s.nmiOccurred;
    this.suppressVbl = s.suppressVbl; this.busAddr = s.busAddr; this.busPrev = s.busPrev ?? s.busAddr;
    this.ntByte = s.ntByte; this.atByte = s.atByte; this.bgLo = s.bgLo; this.bgHi = s.bgHi;
    this.bgShiftLo = s.bgShiftLo; this.bgShiftHi = s.bgShiftHi;
    this.atShiftLo = s.atShiftLo; this.atShiftHi = s.atShiftHi;
    this.oamN = s.oamN; this.oamM = s.oamM; this.oamLatch = s.oamLatch;
    this.secCount = s.secCount; this.evalState = s.evalState; this.ovCopy = s.ovCopy;
    this.sprZeroNext = s.sprZeroNext; this.sprZeroLine = s.sprZeroLine; this.sprCount = s.sprCount;
    return this;
  }

  snapshot() { return this.getState(); }
  restore(s) { return this.setState(s); }
}

// $3F10/$14/$18/$1C are mirrors of $3F00/$04/$08/$0C — the four "backdrop"
// entries are one and the same, which is why writing the sprite backdrop
// changes the background colour.
function palIdx(addr) {
  const a = addr & 0x1f;
  return (a & 0x13) === 0x10 ? a & 0x0f : a;
}

const REVERSE = (() => {
  const t = new Uint8Array(256);
  for (let i = 0; i < 256; i++) {
    let v = 0;
    for (let b = 0; b < 8; b++) if (i & (1 << b)) v |= 0x80 >> b;
    t[i] = v;
  }
  return t;
})();

function reverseByte(b) { return REVERSE[b & 0xff]; }

export function createNesPpu(mapper, opts) { return new NesPpu(mapper, opts); }
