// GENERATED by tools/gen-romlabel-meta.mjs — do not edit by hand.
//
// Machine-verified facts per labeled ROM routine, produced by running
// z80anal over the actual dumps. Notes on reading it honestly:
// - the analysis is a LINEAR SWEEP from each label to the next one
//   ('sweptTo'), so a routine ending early in that span over-approximates
// - 'clobbers' = written and not push/pop-protected; propagation through
//   CALLs is NOT applied here (see z80anal for the transitive version)
// - this file contains our analysis of the ROMs, not the ROMs

export const SCHEMA_VERSION = 1;

export const ROM_LABEL_META = {
 "n88-fr": {
  "14043": {
   "clobbers": [
    "A",
    "F"
   ],
   "inputs": [],
   "saves": [],
   "io": [
    {
     "dir": "in",
     "port": 64,
     "name": "in: VRTC/strobe, out: misc"
    }
   ],
   "mem": [],
   "tStates": {
    "min": 35,
    "max": 35,
    "loop": false
   },
   "warnings": 0,
   "unknown": false,
   "sweptTo": 14050
  },
  "14050": {
   "clobbers": [
    "A",
    "F",
    "B",
    "C",
    "D"
   ],
   "inputs": [
    "A",
    "F",
    "B",
    "C",
    "D",
    "E"
   ],
   "saves": [],
   "io": [
    {
     "dir": "out",
     "port": 255,
     "name": "FDD sub-system 8255 (main side)"
    }
   ],
   "mem": [
    {
     "addr": 60596,
     "name": "GVRAM window (when banked in)"
    },
    {
     "addr": 61204,
     "name": "disk work area"
    }
   ],
   "tStates": {
    "min": 170,
    "max": 180,
    "loop": false
   },
   "warnings": 0,
   "unknown": true,
   "sweptTo": 14080
  },
  "14080": {
   "clobbers": [
    "A",
    "F",
    "B",
    "C",
    "D"
   ],
   "inputs": [],
   "saves": [],
   "io": [],
   "mem": [
    {
     "addr": 61204,
     "name": "disk work area"
    }
   ],
   "tStates": {
    "min": 151,
    "max": 161,
    "loop": true
   },
   "warnings": 0,
   "unknown": true,
   "sweptTo": 14114
  },
  "14114": {
   "clobbers": [
    "A",
    "F",
    "B",
    "C",
    "D"
   ],
   "inputs": [
    "B",
    "C"
   ],
   "saves": [],
   "io": [],
   "mem": [
    {
     "addr": 61258,
     "name": "disk work area"
    },
    {
     "addr": 61279,
     "name": "disk work area"
    }
   ],
   "tStates": {
    "min": 129,
    "max": 129,
    "loop": false
   },
   "warnings": 0,
   "unknown": true,
   "sweptTo": 14138
  },
  "14138": {
   "clobbers": [
    "A",
    "F",
    "B",
    "C",
    "D",
    "E"
   ],
   "inputs": [
    "B",
    "D",
    "E"
   ],
   "saves": [],
   "io": [],
   "mem": [
    {
     "addr": 61277,
     "name": "disk work area"
    }
   ],
   "tStates": {
    "min": 120,
    "max": 135,
    "loop": true
   },
   "warnings": 0,
   "unknown": true,
   "sweptTo": 14164
  },
  "14182": {
   "clobbers": [
    "A",
    "F",
    "B",
    "C",
    "D",
    "E"
   ],
   "inputs": [
    "B",
    "D",
    "E"
   ],
   "saves": [],
   "io": [],
   "mem": [
    {
     "addr": 61277,
     "name": "disk work area"
    }
   ],
   "tStates": {
    "min": 96,
    "max": 111,
    "loop": true
   },
   "warnings": 0,
   "unknown": true,
   "sweptTo": 14203
  },
  "14224": {
   "clobbers": [
    "A",
    "F",
    "B",
    "C",
    "D",
    "E",
    "H",
    "L"
   ],
   "inputs": [],
   "saves": [],
   "io": [],
   "mem": [
    {
     "addr": 60596,
     "name": "GVRAM window (when banked in)"
    },
    {
     "addr": 60596,
     "name": "GVRAM window (when banked in)"
    },
    {
     "addr": 60598,
     "name": "GVRAM window (when banked in)"
    },
    {
     "addr": 60586,
     "name": "GVRAM window (when banked in)"
    },
    {
     "addr": 60588,
     "name": "GVRAM window (when banked in)"
    }
   ],
   "tStates": {
    "min": 301,
    "max": 313,
    "loop": false
   },
   "warnings": 1,
   "unknown": true,
   "sweptTo": 14281
  },
  "14281": {
   "clobbers": [
    "B",
    "C",
    "D"
   ],
   "inputs": [
    "A",
    "F",
    "B",
    "C",
    "D",
    "E"
   ],
   "saves": [
    "A",
    "F"
   ],
   "io": [
    {
     "dir": "out",
     "port": 255,
     "name": "FDD sub-system 8255 (main side)"
    },
    {
     "dir": "in",
     "port": 254,
     "name": "FDD sub-system 8255 (main side)"
    }
   ],
   "mem": [
    {
     "addr": 61204,
     "name": "disk work area"
    }
   ],
   "tStates": {
    "min": 189,
    "max": 199,
    "loop": true
   },
   "warnings": 0,
   "unknown": true,
   "sweptTo": 14318
  },
  "14379": {
   "clobbers": [
    "A",
    "F",
    "B",
    "C",
    "D"
   ],
   "inputs": [
    "B",
    "C",
    "D"
   ],
   "saves": [],
   "io": [],
   "mem": [
    {
     "addr": 61200,
     "name": "disk work area"
    },
    {
     "addr": 61282,
     "name": "disk work area"
    }
   ],
   "tStates": {
    "min": 90,
    "max": 113,
    "loop": false
   },
   "warnings": 1,
   "unknown": true,
   "sweptTo": 14398
  },
  "14407": {
   "clobbers": [
    "A",
    "F",
    "B",
    "C",
    "D"
   ],
   "inputs": [
    "A",
    "F",
    "B",
    "C",
    "D",
    "E"
   ],
   "saves": [],
   "io": [
    {
     "dir": "out",
     "port": 255,
     "name": "FDD sub-system 8255 (main side)"
    },
    {
     "dir": "in",
     "port": 254,
     "name": "FDD sub-system 8255 (main side)"
    }
   ],
   "mem": [],
   "tStates": {
    "min": 122,
    "max": 127,
    "loop": true
   },
   "warnings": 0,
   "unknown": true,
   "sweptTo": 14430
  },
  "15028": {
   "clobbers": [
    "A",
    "F"
   ],
   "inputs": [
    "A",
    "F"
   ],
   "saves": [],
   "io": [],
   "mem": [],
   "tStates": {
    "min": 66,
    "max": 66,
    "loop": false
   },
   "warnings": 0,
   "unknown": true,
   "sweptTo": 15038
  },
  "15038": {
   "clobbers": [
    "A",
    "F",
    "B",
    "D",
    "E",
    "H",
    "L",
    "IY"
   ],
   "inputs": [
    "A",
    "F",
    "B",
    "C",
    "D",
    "E",
    "H",
    "L",
    "IY",
    "SP"
   ],
   "saves": [],
   "io": [],
   "mem": [],
   "tStates": {
    "min": 296,
    "max": 296,
    "loop": false
   },
   "warnings": 0,
   "unknown": true,
   "sweptTo": 15084
  },
  "15552": {
   "clobbers": [
    "A",
    "F",
    "B",
    "C",
    "H",
    "L"
   ],
   "inputs": [
    "B",
    "D",
    "E",
    "H",
    "L",
    "SP"
   ],
   "saves": [
    "D",
    "E"
   ],
   "io": [
    {
     "dir": "in",
     "port": 49,
     "name": "memory/graphics: ROM/RAM, GVRAM on, color"
    }
   ],
   "mem": [],
   "tStates": {
    "min": 348,
    "max": 368,
    "loop": true
   },
   "warnings": 0,
   "unknown": false,
   "sweptTo": 15615
  },
  "15806": {
   "clobbers": [
    "H",
    "L"
   ],
   "inputs": [
    "A",
    "F",
    "H",
    "L",
    "SP"
   ],
   "saves": [
    "A",
    "F"
   ],
   "io": [
    {
     "dir": "out",
     "port": 50,
     "name": "ext-ROM bank / palette mode (SR)"
    },
    {
     "dir": "out",
     "port": 113,
     "name": "ext ROM select"
    }
   ],
   "mem": [],
   "tStates": {
    "min": 98,
    "max": 98,
    "loop": false
   },
   "warnings": 1,
   "unknown": false,
   "sweptTo": 15819
  },
  "17745": {
   "clobbers": [
    "H",
    "L"
   ],
   "inputs": [
    "A",
    "F",
    "D",
    "E",
    "H",
    "L",
    "SP"
   ],
   "saves": [
    "A",
    "F",
    "D",
    "E"
   ],
   "io": [
    {
     "dir": "in",
     "port": 113,
     "name": "ext ROM select"
    },
    {
     "dir": "out",
     "port": 113,
     "name": "ext ROM select"
    }
   ],
   "mem": [
    {
     "addr": 61195,
     "name": "disk work area"
    },
    {
     "addr": 61194,
     "name": "disk work area"
    },
    {
     "addr": 61194,
     "name": "disk work area"
    },
    {
     "addr": 61195,
     "name": "disk work area"
    }
   ],
   "tStates": {
    "min": 306,
    "max": 306,
    "loop": false
   },
   "warnings": 1,
   "unknown": true,
   "sweptTo": 17793
  },
  "17793": {
   "clobbers": [
    "A",
    "H",
    "L"
   ],
   "inputs": [
    "A",
    "H",
    "L",
    "SP"
   ],
   "saves": [],
   "io": [
    {
     "dir": "out",
     "port": 113,
     "name": "ext ROM select"
    }
   ],
   "mem": [
    {
     "addr": 61194,
     "name": "disk work area"
    },
    {
     "addr": 61194,
     "name": "disk work area"
    }
   ],
   "tStates": {
    "min": 88,
    "max": 88,
    "loop": false
   },
   "warnings": 1,
   "unknown": false,
   "sweptTo": 17807
  },
  "28422": {
   "clobbers": [
    "A",
    "F",
    "D",
    "E",
    "H",
    "L"
   ],
   "inputs": [
    "E"
   ],
   "saves": [],
   "io": [],
   "mem": [],
   "tStates": {
    "min": 21,
    "max": 21,
    "loop": false
   },
   "warnings": 0,
   "unknown": true,
   "sweptTo": 28426
  },
  "28426": {
   "clobbers": [
    "A",
    "F",
    "B",
    "C",
    "D",
    "E",
    "H",
    "L"
   ],
   "inputs": [
    "E"
   ],
   "saves": [],
   "io": [],
   "mem": [],
   "tStates": {
    "min": 102,
    "max": 102,
    "loop": false
   },
   "warnings": 1,
   "unknown": true,
   "sweptTo": 28446
  },
  "29389": {
   "clobbers": [
    "A",
    "F",
    "B",
    "C",
    "D",
    "E",
    "H",
    "L"
   ],
   "inputs": [
    "A"
   ],
   "saves": [],
   "io": [
    {
     "dir": "out",
     "port": 230,
     "name": "interrupt mask"
    },
    {
     "dir": "out",
     "port": 48,
     "name": "system: 40/80col, CMT motor"
    },
    {
     "dir": "out",
     "port": 64,
     "name": "in: VRTC/strobe, out: misc"
    },
    {
     "dir": "out",
     "port": 49,
     "name": "memory/graphics: ROM/RAM, GVRAM on, color"
    },
    {
     "dir": "out",
     "port": 235,
     "name": null
    },
    {
     "dir": "out",
     "port": 193,
     "name": null
    },
    {
     "dir": "out",
     "port": 195,
     "name": null
    },
    {
     "dir": "out",
     "port": 200,
     "name": null
    },
    {
     "dir": "out",
     "port": 202,
     "name": null
    },
    {
     "dir": "out",
     "port": 228,
     "name": "interrupt level (μPD8214)"
    }
   ],
   "mem": [
    {
     "addr": 59072,
     "name": "GVRAM window (when banked in)"
    },
    {
     "addr": 59073,
     "name": "GVRAM window (when banked in)"
    },
    {
     "addr": 59074,
     "name": "GVRAM window (when banked in)"
    },
    {
     "addr": 61282,
     "name": "disk work area"
    },
    {
     "addr": 61200,
     "name": "disk work area"
    },
    {
     "addr": 61458,
     "name": "GVRAM window (when banked in)"
    },
    {
     "addr": 59075,
     "name": "GVRAM window (when banked in)"
    },
    {
     "addr": 61277,
     "name": "disk work area"
    },
    {
     "addr": 61198,
     "name": "disk work area"
    }
   ],
   "tStates": {
    "min": 547,
    "max": 554,
    "loop": true
   },
   "warnings": 0,
   "unknown": true,
   "sweptTo": 29506
  },
  "30031": {
   "clobbers": [
    "A",
    "F",
    "C",
    "E",
    "H",
    "L"
   ],
   "inputs": [
    "A"
   ],
   "saves": [],
   "io": [],
   "mem": [
    {
     "addr": 61280,
     "name": "disk work area"
    },
    {
     "addr": 61281,
     "name": "disk work area"
    },
    {
     "addr": 61280,
     "name": "disk work area"
    },
    {
     "addr": 61281,
     "name": "disk work area"
    },
    {
     "addr": 61283,
     "name": "disk work area"
    },
    {
     "addr": 61282,
     "name": "disk work area"
    },
    {
     "addr": 60541,
     "name": "GVRAM window (when banked in)"
    }
   ],
   "tStates": {
    "min": 271,
    "max": 276,
    "loop": false
   },
   "warnings": 0,
   "unknown": true,
   "sweptTo": 30090
  },
  "30113": {
   "clobbers": [
    "A",
    "F"
   ],
   "inputs": [],
   "saves": [],
   "io": [],
   "mem": [
    {
     "addr": 61204,
     "name": "disk work area"
    },
    {
     "addr": 61200,
     "name": "disk work area"
    },
    {
     "addr": 61283,
     "name": "disk work area"
    }
   ],
   "tStates": {
    "min": 282,
    "max": 288,
    "loop": false
   },
   "warnings": 0,
   "unknown": true,
   "sweptTo": 30173
  },
  "30730": {
   "clobbers": [
    "A",
    "F",
    "B",
    "C",
    "D",
    "E",
    "H",
    "L"
   ],
   "inputs": [],
   "saves": [],
   "io": [
    {
     "dir": "in",
     "port": 9,
     "name": "keyboard matrix"
    }
   ],
   "mem": [
    {
     "addr": 61311,
     "name": "disk work area"
    }
   ],
   "tStates": {
    "min": 89,
    "max": 94,
    "loop": false
   },
   "warnings": 0,
   "unknown": true,
   "sweptTo": 30752
  }
 },
 "pc80s31": {
  "177": {
   "clobbers": [
    "A",
    "F",
    "B",
    "H",
    "L",
    "SP"
   ],
   "inputs": [],
   "saves": [],
   "io": [
    {
     "dir": "out",
     "port": 255,
     "name": "FDD sub-system 8255 (sub side)"
    },
    {
     "dir": "in",
     "port": 254,
     "name": "FDD sub-system 8255 (sub side)"
    }
   ],
   "mem": [
    {
     "addr": 32521,
     "name": null
    }
   ],
   "tStates": {
    "min": 113,
    "max": 118,
    "loop": true
   },
   "warnings": 0,
   "unknown": false,
   "sweptTo": 204
  },
  "204": {
   "clobbers": [
    "A",
    "F",
    "B",
    "H",
    "L"
   ],
   "inputs": [
    "B",
    "H",
    "L"
   ],
   "saves": [],
   "io": [
    {
     "dir": "in",
     "port": 254,
     "name": "FDD sub-system 8255 (sub side)"
    }
   ],
   "mem": [
    {
     "addr": 32521,
     "name": null
    }
   ],
   "tStates": {
    "min": 98,
    "max": 118,
    "loop": true
   },
   "warnings": 0,
   "unknown": true,
   "sweptTo": 228
  },
  "236": {
   "clobbers": [
    "B",
    "C",
    "H",
    "L"
   ],
   "inputs": [
    "A"
   ],
   "saves": [
    "A",
    "F"
   ],
   "io": [
    {
     "dir": "out",
     "port": 248,
     "name": "in: FDC TC pulse / out: drive motors"
    }
   ],
   "mem": [
    {
     "addr": 32521,
     "name": null
    },
    {
     "addr": 32521,
     "name": null
    },
    {
     "addr": 32534,
     "name": null
    }
   ],
   "tStates": {
    "min": 242,
    "max": 253,
    "loop": false
   },
   "warnings": 0,
   "unknown": true,
   "sweptTo": 283
  },
  "283": {
   "clobbers": [
    "A",
    "F",
    "B",
    "C",
    "D",
    "E",
    "L",
    "SP"
   ],
   "inputs": [
    "A",
    "F",
    "H",
    "L",
    "SP"
   ],
   "saves": [],
   "io": [
    {
     "dir": "out",
     "port": 247,
     "name": "printer port (unused)"
    }
   ],
   "mem": [],
   "tStates": {
    "min": 265,
    "max": 277,
    "loop": false
   },
   "warnings": 0,
   "unknown": true,
   "sweptTo": 349
  },
  "349": {
   "clobbers": [
    "C",
    "D"
   ],
   "inputs": [],
   "saves": [
    "A",
    "F"
   ],
   "io": [],
   "mem": [
    {
     "addr": 32533,
     "name": null
    },
    {
     "addr": 32532,
     "name": null
    },
    {
     "addr": 32533,
     "name": null
    }
   ],
   "tStates": {
    "min": 281,
    "max": 298,
    "loop": true
   },
   "warnings": 0,
   "unknown": true,
   "sweptTo": 406
  },
  "676": {
   "clobbers": [],
   "inputs": [
    "A",
    "F"
   ],
   "saves": [
    "A",
    "F"
   ],
   "io": [
    {
     "dir": "in",
     "port": 250,
     "name": "μPD765 FDC status"
    },
    {
     "dir": "out",
     "port": 251,
     "name": "μPD765 FDC data"
    }
   ],
   "mem": [
    {
     "addr": 32524,
     "name": null
    }
   ],
   "tStates": {
    "min": 87,
    "max": 92,
    "loop": true
   },
   "warnings": 0,
   "unknown": false,
   "sweptTo": 692
  },
  "692": {
   "clobbers": [
    "A",
    "F"
   ],
   "inputs": [
    "H",
    "L"
   ],
   "saves": [
    "H",
    "L"
   ],
   "io": [],
   "mem": [],
   "tStates": {
    "min": 79,
    "max": 84,
    "loop": true
   },
   "warnings": 0,
   "unknown": true,
   "sweptTo": 706
  },
  "1468": {
   "clobbers": [
    "B",
    "H",
    "L"
   ],
   "inputs": [
    "A",
    "F"
   ],
   "saves": [
    "A",
    "F"
   ],
   "io": [],
   "mem": [
    {
     "addr": 32539,
     "name": null
    }
   ],
   "tStates": {
    "min": 101,
    "max": 106,
    "loop": true
   },
   "warnings": 0,
   "unknown": true,
   "sweptTo": 1486
  },
  "1498": {
   "clobbers": [
    "A",
    "F",
    "B",
    "C",
    "D",
    "E",
    "H",
    "L",
    "IX",
    "IY",
    "SP",
    "I"
   ],
   "inputs": [],
   "saves": [],
   "io": [],
   "mem": [
    {
     "addr": 32554,
     "name": null
    },
    {
     "addr": 32550,
     "name": null
    },
    {
     "addr": 32549,
     "name": null
    },
    {
     "addr": 32556,
     "name": null
    },
    {
     "addr": 32552,
     "name": null
    }
   ],
   "tStates": {
    "min": 230,
    "max": 230,
    "loop": false
   },
   "warnings": 0,
   "unknown": true,
   "sweptTo": 1538
  },
  "1702": {
   "clobbers": [
    "B",
    "C",
    "D",
    "E"
   ],
   "inputs": [
    "A"
   ],
   "saves": [],
   "io": [],
   "mem": [],
   "tStates": {
    "min": 70,
    "max": 70,
    "loop": false
   },
   "warnings": 0,
   "unknown": true,
   "sweptTo": 1711
  },
  "1807": {
   "clobbers": [
    "A",
    "F"
   ],
   "inputs": [
    "A",
    "F"
   ],
   "saves": [],
   "io": [
    {
     "dir": "in",
     "port": 254,
     "name": "FDD sub-system 8255 (sub side)"
    }
   ],
   "mem": [],
   "tStates": {
    "min": 67,
    "max": 72,
    "loop": true
   },
   "warnings": 0,
   "unknown": true,
   "sweptTo": 1821
  }
 }
};
