// GENERATED by tools/gen-romxref.mjs — do not edit by hand.
//
// Static call hierarchy + work-variable cross-reference for the labeled
// ROMs, discovered to a fixpoint (every call target becomes a routine).
// Unlabeled routines carry auto names (L####). Same honesty rules as
// romlabels-meta.js: linear sweeps, no guessing past indirect flow.
// This file contains our analysis of the ROMs, not the ROMs.

export const SCHEMA_VERSION = 1;

export const ROM_XREF = {
 "n88-fr": {
  "routines": {
   "0": {
    "name": "L0000",
    "calls": [
     15333
    ],
    "callers": [
     "L0106"
    ],
    "size": 7
   },
   "8": {
    "name": "L0008",
    "calls": [
     915
    ],
    "callers": [
     "L0C9C",
     "L11CE",
     "L585A",
     "L58D6"
    ],
    "size": 8
   },
   "16": {
    "name": "L0010",
    "calls": [
     2581
    ],
    "callers": [
     "L09E5",
     "L0B34",
     "L0B4F",
     "L18A3",
     "L1ABF",
     "L1BBB",
     "L2907",
     "L2A5A",
     "L53F6",
     "L5441",
     "L5ACA"
    ],
    "size": 8
   },
   "24": {
    "name": "L0018",
    "calls": [
     60738,
     22821
    ],
    "callers": [
     "L0451",
     "L045F",
     "L04A7",
     "L0996",
     "L3A8F",
     "L512B",
     "L5A69",
     "L5FD8",
     "L6568",
     "L661C"
    ],
    "size": 7
   },
   "32": {
    "name": "L0020",
    "calls": [],
    "callers": [
     "L045F",
     "L0605",
     "L0B4F",
     "L0C9C",
     "L1933",
     "L537D",
     "L54FC",
     "L5572",
     "L56CC",
     "L56E7",
     "L585A",
     "L76D3",
     "L776C",
     "L777A"
    ],
    "size": 6
   },
   "40": {
    "name": "L0028",
    "calls": [
     8323
    ],
    "callers": [
     "L1B9D",
     "L20BD",
     "L2553"
    ],
    "size": 8
   },
   "48": {
    "name": "L0030",
    "calls": [
     5415
    ],
    "callers": [
     "L1B9D",
     "L20A4",
     "L20BD",
     "L212A",
     "L2214",
     "L29F0",
     "L2BC8",
     "L2C7D"
    ],
    "size": 8
   },
   "262": {
    "name": "L0106",
    "calls": [
     65534,
     24662,
     0
    ],
    "callers": [
     "L2DBC"
    ],
    "size": 36
   },
   "879": {
    "name": "L036F",
    "calls": [
     1011
    ],
    "callers": [
     "boot_stop_key_fork"
    ],
    "size": 6
   },
   "885": {
    "name": "L0375",
    "calls": [
     60741,
     947,
     20731
    ],
    "callers": [
     "L0996"
    ],
    "size": 22
   },
   "915": {
    "name": "L0393",
    "calls": [],
    "callers": [
     "L0008",
     "L06D0",
     "L0996",
     "L1499",
     "L17C9",
     "L5ACA"
    ],
    "size": 5
   },
   "918": {
    "name": "L0396",
    "calls": [],
    "callers": [
     "L06D0"
    ],
    "size": 5
   },
   "921": {
    "name": "L0399",
    "calls": [],
    "callers": [
     "L5441"
    ],
    "size": 26
   },
   "945": {
    "name": "L03B1",
    "calls": [],
    "callers": [
     "L11D3",
     "L20A4",
     "L20BD",
     "L2214"
    ],
    "size": 2
   },
   "947": {
    "name": "L03B3",
    "calls": [
     17621,
     60873
    ],
    "callers": [
     "L0375",
     "L0B06",
     "L0C3C",
     "L4DB5",
     "L4EC1",
     "L54FC",
     "L5680",
     "L7CCD"
    ],
    "size": 64
   },
   "1011": {
    "name": "L03F3",
    "calls": [
     20404
    ],
    "callers": [
     "L036F"
    ],
    "size": 6
   },
   "1085": {
    "name": "L043D",
    "calls": [
     15014
    ],
    "callers": [
     "L04A7",
     "L3D75"
    ],
    "size": 20
   },
   "1105": {
    "name": "L0451",
    "calls": [
     24,
     14820
    ],
    "callers": [
     "L045F"
    ],
    "size": 14
   },
   "1119": {
    "name": "L045F",
    "calls": [
     60777,
     1105,
     32,
     30711,
     10426,
     24
    ],
    "callers": [
     "L50FB"
    ],
    "size": 28
   },
   "1146": {
    "name": "L047A",
    "calls": [
     22921,
     30170,
     19627,
     60744,
     3979,
     23128,
     21840,
     25960
    ],
    "callers": [
     "L50FB"
    ],
    "size": 45
   },
   "1191": {
    "name": "L04A7",
    "calls": [
     60735,
     1085,
     31949,
     10434,
     1541,
     24,
     24466
    ],
    "callers": [
     "L6568"
    ],
    "size": 59
   },
   "1541": {
    "name": "L0605",
    "calls": [
     17572,
     17635,
     32,
     17602
    ],
    "callers": [
     "L04A7",
     "L1BBB",
     "L50A5",
     "L6568"
    ],
    "size": 45
   },
   "1586": {
    "name": "L0632",
    "calls": [
     60702
    ],
    "callers": [
     "L75AA"
    ],
    "size": 39
   },
   "1744": {
    "name": "L06D0",
    "calls": [
     918,
     915
    ],
    "callers": [
     "L53D2"
    ],
    "size": 19
   },
   "1763": {
    "name": "L06E3",
    "calls": [
     10307
    ],
    "callers": [
     "L283C"
    ],
    "size": 8
   },
   "2454": {
    "name": "L0996",
    "calls": [
     31949,
     60876,
     20569,
     23174,
     17621,
     2533,
     915,
     17635,
     885,
     24,
     10434
    ],
    "callers": [
     "L7497"
    ],
    "size": 79
   },
   "2533": {
    "name": "L09E5",
    "calls": [
     16,
     21632,
     3228,
     6089
    ],
    "callers": [
     "L0996",
     "L4C70"
    ],
    "size": 40
   },
   "2573": {
    "name": "L0A0D",
    "calls": [],
    "callers": [
     "L0A15",
     "L0B0B",
     "L0B4F",
     "L1499",
     "L54FC"
    ],
    "size": 8
   },
   "2581": {
    "name": "L0A15",
    "calls": [
     2573
    ],
    "callers": [
     "L0010"
    ],
    "size": 21
   },
   "2701": {
    "name": "L0A8D",
    "calls": [
     9218
    ],
    "callers": [
     "L1ABF"
    ],
    "size": 26
   },
   "2822": {
    "name": "L0B06",
    "calls": [
     947
    ],
    "callers": [
     "L18A3",
     "L431E",
     "L4F21",
     "L585A",
     "L6568"
    ],
    "size": 5
   },
   "2827": {
    "name": "L0B0B",
    "calls": [
     2573,
     2868,
     17621,
     17572
    ],
    "callers": [
     "L50A5",
     "L6568"
    ],
    "size": 41
   },
   "2868": {
    "name": "L0B34",
    "calls": [
     16,
     21569
    ],
    "callers": [
     "L0B0B"
    ],
    "size": 21
   },
   "2895": {
    "name": "L0B4F",
    "calls": [
     2573,
     16,
     32
    ],
    "callers": [
     "L1BBB"
    ],
    "size": 42
   },
   "3132": {
    "name": "L0C3C",
    "calls": [
     947
    ],
    "callers": [
     "L50A5",
     "L6568"
    ],
    "size": 5
   },
   "3228": {
    "name": "L0C9C",
    "calls": [
     23242,
     8,
     4563,
     6038,
     32,
     22247,
     21720,
     8444
    ],
    "callers": [
     "L09E5"
    ],
    "size": 101
   },
   "3979": {
    "name": "L0F8B",
    "calls": [
     60723,
     32533,
     32538
    ],
    "callers": [
     "L047A",
     "L4FB4"
    ],
    "size": 31
   },
   "4558": {
    "name": "L11CE",
    "calls": [
     8
    ],
    "callers": [
     "L585A"
    ],
    "size": 5
   },
   "4563": {
    "name": "L11D3",
    "calls": [
     20161,
     60726,
     4944,
     22144,
     60789,
     945
    ],
    "callers": [
     "L0C9C",
     "L18A3"
    ],
    "size": 141
   },
   "4944": {
    "name": "L1350",
    "calls": [
     4958
    ],
    "callers": [
     "L11D3",
     "L5680"
    ],
    "size": 14
   },
   "5273": {
    "name": "L1499",
    "calls": [
     915,
     2573
    ],
    "callers": [
     "L17C9"
    ],
    "size": 20
   },
   "5360": {
    "name": "L14F0",
    "calls": [],
    "callers": [
     "L1796"
    ],
    "size": 6
   },
   "5415": {
    "name": "L1527",
    "calls": [],
    "callers": [
     "L0030"
    ],
    "size": 7
   },
   "6038": {
    "name": "L1796",
    "calls": [
     5360
    ],
    "callers": [
     "L0C9C"
    ],
    "size": 15
   },
   "6089": {
    "name": "L17C9",
    "calls": [
     915,
     22618,
     5273
    ],
    "callers": [
     "L09E5"
    ],
    "size": 25
   },
   "6272": {
    "name": "L1880",
    "calls": [
     6283
    ],
    "callers": [
     "L6F6A"
    ],
    "size": 11
   },
   "6283": {
    "name": "L188B",
    "calls": [],
    "callers": [
     "L1880"
    ],
    "size": 10
   },
   "6307": {
    "name": "L18A3",
    "calls": [
     4563,
     6297,
     2822,
     16
    ],
    "callers": [
     "L585A",
     "L58D6"
    ],
    "size": 13
   },
   "6451": {
    "name": "L1933",
    "calls": [
     32,
     26140
    ],
    "callers": [
     "L6568"
    ],
    "size": 25
   },
   "6476": {
    "name": "L194C",
    "calls": [
     60840,
     6836,
     6847
    ],
    "callers": [
     "L6568"
    ],
    "size": 135
   },
   "6836": {
    "name": "L1AB4",
    "calls": [
     21014
    ],
    "callers": [
     "L194C"
    ],
    "size": 11
   },
   "6847": {
    "name": "L1ABF",
    "calls": [
     16,
     2701,
     11708,
     11711,
     10448
    ],
    "callers": [
     "L194C"
    ],
    "size": 29
   },
   "7069": {
    "name": "L1B9D",
    "calls": [
     48,
     60729,
     40,
     8724,
     7657
    ],
    "callers": [
     "L2DBF"
    ],
    "size": 29
   },
   "7099": {
    "name": "L1BBB",
    "calls": [
     17572,
     17621,
     16,
     60801,
     2895,
     1541,
     17587,
     23128,
     21840,
     10434,
     10426
    ],
    "callers": [
     "L1C81"
    ],
    "size": 126
   },
   "7297": {
    "name": "L1C81",
    "calls": [
     7099
    ],
    "callers": [
     "L6568"
    ],
    "size": 8
   },
   "7636": {
    "name": "L1DD4",
    "calls": [],
    "callers": [
     "L4FB4"
    ],
    "size": 7
   },
   "7643": {
    "name": "L1DDB",
    "calls": [
     8427,
     7657
    ],
    "callers": [
     "L2C7D"
    ],
    "size": 8
   },
   "7657": {
    "name": "L1DE9",
    "calls": [
     8413,
     60852,
     8397,
     8455,
     7867,
     7835,
     7804,
     10300,
     7901
    ],
    "callers": [
     "L1B9D",
     "L1DDB"
    ],
    "size": 65
   },
   "7736": {
    "name": "L1E38",
    "calls": [
     7847,
     7786
    ],
    "callers": [
     "L2092"
    ],
    "size": 22
   },
   "7758": {
    "name": "L1E4E",
    "calls": [],
    "callers": [
     "L1E6A",
     "L2065",
     "L248C",
     "L2553"
    ],
    "size": 5
   },
   "7786": {
    "name": "L1E6A",
    "calls": [
     7763,
     7804,
     7758
    ],
    "callers": [
     "L1E38"
    ],
    "size": 18
   },
   "7804": {
    "name": "L1E7C",
    "calls": [
     7822,
     8413
    ],
    "callers": [
     "L1DE9",
     "L1E6A",
     "L2214"
    ],
    "size": 18
   },
   "7822": {
    "name": "L1E8E",
    "calls": [
     10299
    ],
    "callers": [
     "L1E7C",
     "L225B"
    ],
    "size": 13
   },
   "7835": {
    "name": "L1E9B",
    "calls": [],
    "callers": [
     "L1DE9",
     "L2C7D"
    ],
    "size": 12
   },
   "7847": {
    "name": "L1EA7",
    "calls": [],
    "callers": [
     "L1E38",
     "L225B"
    ],
    "size": 20
   },
   "7867": {
    "name": "L1EBB",
    "calls": [],
    "callers": [
     "L1DE9",
     "L225B"
    ],
    "size": 13
   },
   "7897": {
    "name": "L1ED9",
    "calls": [],
    "callers": [
     "L1EDD"
    ],
    "size": 4
   },
   "7901": {
    "name": "L1EDD",
    "calls": [
     7897
    ],
    "callers": [
     "L1DE9"
    ],
    "size": 13
   },
   "8101": {
    "name": "L1FA5",
    "calls": [],
    "callers": [
     "L203A"
    ],
    "size": 2
   },
   "8250": {
    "name": "L203A",
    "calls": [
     8293,
     8292,
     8101,
     8455
    ],
    "callers": [
     "L2553"
    ],
    "size": 37
   },
   "8287": {
    "name": "L205F",
    "calls": [],
    "callers": [
     "L2A5A"
    ],
    "size": 2
   },
   "8292": {
    "name": "L2064",
    "calls": [],
    "callers": [
     "L203A"
    ],
    "size": 1
   },
   "8293": {
    "name": "L2065",
    "calls": [
     7758,
     10272
    ],
    "callers": [
     "L203A"
    ],
    "size": 7
   },
   "8323": {
    "name": "L2083",
    "calls": [],
    "callers": [
     "L0028"
    ],
    "size": 5
   },
   "8328": {
    "name": "L2088",
    "calls": [],
    "callers": [
     "L20BD"
    ],
    "size": 5
   },
   "8338": {
    "name": "L2092",
    "calls": [
     7736
    ],
    "callers": [
     "L2402"
    ],
    "size": 14
   },
   "8356": {
    "name": "L20A4",
    "calls": [
     48,
     9207,
     945
    ],
    "callers": [
     "L28D0"
    ],
    "size": 7
   },
   "8363": {
    "name": "L20AB",
    "calls": [],
    "callers": [],
    "size": 8
   },
   "8381": {
    "name": "L20BD",
    "calls": [
     48,
     945,
     40,
     8328
    ],
    "callers": [
     "L28D0"
    ],
    "size": 16
   },
   "8397": {
    "name": "L20CD",
    "calls": [],
    "callers": [
     "L1DE9",
     "L2954"
    ],
    "size": 13
   },
   "8410": {
    "name": "L20DA",
    "calls": [
     8427
    ],
    "callers": [
     "L2C7D"
    ],
    "size": 3
   },
   "8413": {
    "name": "L20DD",
    "calls": [],
    "callers": [
     "L1DE9",
     "L1E7C",
     "L2C7D"
    ],
    "size": 11
   },
   "8424": {
    "name": "L20E8",
    "calls": [],
    "callers": [
     "L2214",
     "L225B",
     "L22DD",
     "L2C7D"
    ],
    "size": 3
   },
   "8427": {
    "name": "L20EB",
    "calls": [],
    "callers": [
     "L1DDB",
     "L20DA"
    ],
    "size": 2
   },
   "8429": {
    "name": "L20ED",
    "calls": [],
    "callers": [
     "L5550"
    ],
    "size": 5
   },
   "8434": {
    "name": "L20F2",
    "calls": [],
    "callers": [
     "L29F0"
    ],
    "size": 2
   },
   "8439": {
    "name": "L20F7",
    "calls": [
     8448
    ],
    "callers": [
     "L4F21"
    ],
    "size": 4
   },
   "8444": {
    "name": "L20FC",
    "calls": [],
    "callers": [
     "L0C9C",
     "L2BC8",
     "L54FC",
     "L585A"
    ],
    "size": 4
   },
   "8448": {
    "name": "L2100",
    "calls": [],
    "callers": [
     "L20F7"
    ],
    "size": 7
   },
   "8455": {
    "name": "L2107",
    "calls": [],
    "callers": [
     "L1DE9",
     "L203A",
     "L2214",
     "L225B",
     "L22DD",
     "L2424"
    ],
    "size": 21
   },
   "8476": {
    "name": "L211C",
    "calls": [],
    "callers": [
     "L2424"
    ],
    "size": 3
   },
   "8479": {
    "name": "L211F",
    "calls": [
     8490
    ],
    "callers": [
     "L2C7D"
    ],
    "size": 5
   },
   "8484": {
    "name": "L2124",
    "calls": [],
    "callers": [
     "L2C7D"
    ],
    "size": 6
   },
   "8490": {
    "name": "L212A",
    "calls": [
     48
    ],
    "callers": [
     "L211F"
    ],
    "size": 10
   },
   "8701": {
    "name": "L21FD",
    "calls": [],
    "callers": [
     "L23ED",
     "L28C2"
    ],
    "size": 5
   },
   "8706": {
    "name": "L2202",
    "calls": [],
    "callers": [
     "L2252"
    ],
    "size": 4
   },
   "8724": {
    "name": "L2214",
    "calls": [
     48,
     945,
     8424,
     8786,
     8455,
     7804
    ],
    "callers": [
     "L1B9D"
    ],
    "size": 27
   },
   "8786": {
    "name": "L2252",
    "calls": [
     8706
    ],
    "callers": [
     "L2214",
     "L2402"
    ],
    "size": 4
   },
   "8795": {
    "name": "L225B",
    "calls": [
     8424,
     8455,
     8831,
     7867,
     7822,
     7847
    ],
    "callers": [
     "L2C7D"
    ],
    "size": 36
   },
   "8831": {
    "name": "L227F",
    "calls": [],
    "callers": [
     "L225B"
    ],
    "size": 7
   },
   "8925": {
    "name": "L22DD",
    "calls": [
     8424,
     8455,
     8968,
     9499,
     9428,
     9356
    ],
    "callers": [
     "L2C7D"
    ],
    "size": 43
   },
   "8968": {
    "name": "L2308",
    "calls": [],
    "callers": [
     "L22DD"
    ],
    "size": 10
   },
   "9197": {
    "name": "L23ED",
    "calls": [
     8701
    ],
    "callers": [
     "L23F7"
    ],
    "size": 10
   },
   "9207": {
    "name": "L23F7",
    "calls": [
     9197
    ],
    "callers": [
     "L20A4"
    ],
    "size": 11
   },
   "9218": {
    "name": "L2402",
    "calls": [
     8786,
     8338
    ],
    "callers": [
     "L0A8D"
    ],
    "size": 10
   },
   "9252": {
    "name": "L2424",
    "calls": [
     60855,
     8476,
     8455,
     9499,
     9446,
     9410,
     10300,
     9538
    ],
    "callers": [
     "L2C7D"
    ],
    "size": 95
   },
   "9356": {
    "name": "L248C",
    "calls": [
     7758
    ],
    "callers": [
     "L22DD",
     "L2553"
    ],
    "size": 30
   },
   "9410": {
    "name": "L24C2",
    "calls": [
     9428
    ],
    "callers": [
     "L2424"
    ],
    "size": 18
   },
   "9428": {
    "name": "L24D4",
    "calls": [
     10300
    ],
    "callers": [
     "L22DD",
     "L24C2"
    ],
    "size": 18
   },
   "9446": {
    "name": "L24E6",
    "calls": [],
    "callers": [
     "L2424",
     "L2553"
    ],
    "size": 3
   },
   "9449": {
    "name": "L24E9",
    "calls": [],
    "callers": [
     "L2C7D"
    ],
    "size": 15
   },
   "9464": {
    "name": "L24F8",
    "calls": [],
    "callers": [],
    "size": 3
   },
   "9467": {
    "name": "L24FB",
    "calls": [],
    "callers": [
     "L2C7D"
    ],
    "size": 15
   },
   "9482": {
    "name": "L250A",
    "calls": [],
    "callers": [],
    "size": 17
   },
   "9499": {
    "name": "L251B",
    "calls": [],
    "callers": [
     "L22DD",
     "L2424"
    ],
    "size": 20
   },
   "9526": {
    "name": "L2536",
    "calls": [
     9522
    ],
    "callers": [
     "L2542"
    ],
    "size": 12
   },
   "9538": {
    "name": "L2542",
    "calls": [
     9526
    ],
    "callers": [
     "L2424",
     "L2553"
    ],
    "size": 7
   },
   "9555": {
    "name": "L2553",
    "calls": [
     40,
     7758,
     60861,
     8250,
     9866,
     9446,
     9538,
     9356
    ],
    "callers": [
     "L2BC8"
    ],
    "size": 50
   },
   "9866": {
    "name": "L268A",
    "calls": [],
    "callers": [
     "L2553"
    ],
    "size": 19
   },
   "10299": {
    "name": "L283B",
    "calls": [],
    "callers": [
     "L1E8E"
    ],
    "size": 1
   },
   "10300": {
    "name": "L283C",
    "calls": [
     1763
    ],
    "callers": [
     "L1DE9",
     "L2424",
     "L24D4"
    ],
    "size": 16
   },
   "10426": {
    "name": "L28BA",
    "calls": [
     21840
    ],
    "callers": [
     "L045F",
     "L1BBB"
    ],
    "size": 8
   },
   "10434": {
    "name": "L28C2",
    "calls": [
     8701,
     10571,
     10476
    ],
    "callers": [
     "L04A7",
     "L0996",
     "L1BBB",
     "L6568"
    ],
    "size": 14
   },
   "10448": {
    "name": "L28D0",
    "calls": [
     10571,
     8381,
     10476,
     8356
    ],
    "callers": [
     "L1ABF"
    ],
    "size": 28
   },
   "10476": {
    "name": "L28EC",
    "calls": [
     10842,
     10834,
     10580,
     11529
    ],
    "callers": [
     "L28C2",
     "L28D0"
    ],
    "size": 27
   },
   "10503": {
    "name": "L2907",
    "calls": [
     16
    ],
    "callers": [
     "L2A5A"
    ],
    "size": 68
   },
   "10571": {
    "name": "L294B",
    "calls": [],
    "callers": [
     "L28C2",
     "L28D0"
    ],
    "size": 9
   },
   "10580": {
    "name": "L2954",
    "calls": [
     8397,
     10736
    ],
    "callers": [
     "L28EC"
    ],
    "size": 71
   },
   "10736": {
    "name": "L29F0",
    "calls": [
     11208,
     11352,
     8434,
     11389,
     10835,
     48
    ],
    "callers": [
     "L2954"
    ],
    "size": 98
   },
   "10834": {
    "name": "L2A52",
    "calls": [],
    "callers": [
     "L28EC"
    ],
    "size": 1
   },
   "10835": {
    "name": "L2A53",
    "calls": [],
    "callers": [
     "L29F0"
    ],
    "size": 7
   },
   "10842": {
    "name": "L2A5A",
    "calls": [
     11344,
     11312,
     11529,
     8287,
     10503,
     16
    ],
    "callers": [
     "L28EC"
    ],
    "size": 102
   },
   "11208": {
    "name": "L2BC8",
    "calls": [
     48,
     8444,
     9555
    ],
    "callers": [
     "L29F0"
    ],
    "size": 32
   },
   "11312": {
    "name": "L2C30",
    "calls": [],
    "callers": [
     "L2A5A"
    ],
    "size": 8
   },
   "11344": {
    "name": "L2C50",
    "calls": [],
    "callers": [
     "L2A5A"
    ],
    "size": 8
   },
   "11352": {
    "name": "L2C58",
    "calls": [
     11371
    ],
    "callers": [
     "L29F0"
    ],
    "size": 18
   },
   "11370": {
    "name": "L2C6A",
    "calls": [],
    "callers": [
     "L2C7D",
     "L2D0F"
    ],
    "size": 1
   },
   "11371": {
    "name": "L2C6B",
    "calls": [],
    "callers": [
     "L2C58"
    ],
    "size": 10
   },
   "11389": {
    "name": "L2C7D",
    "calls": [
     48,
     8484,
     8479,
     9252,
     8925,
     11370,
     9467,
     9449,
     8410,
     7643,
     8795,
     8413,
     8424,
     7835,
     11535
    ],
    "callers": [
     "L29F0"
    ],
    "size": 140
   },
   "11529": {
    "name": "L2D09",
    "calls": [],
    "callers": [
     "L28EC",
     "L2A5A"
    ],
    "size": 6
   },
   "11535": {
    "name": "L2D0F",
    "calls": [
     11370
    ],
    "callers": [
     "L2C7D"
    ],
    "size": 47
   },
   "11708": {
    "name": "L2DBC",
    "calls": [
     262
    ],
    "callers": [
     "L1ABF"
    ],
    "size": 5
   },
   "11711": {
    "name": "L2DBF",
    "calls": [
     7069
    ],
    "callers": [
     "L1ABF"
    ],
    "size": 62
   },
   "13528": {
    "name": "L34D8",
    "calls": [
     13559
    ],
    "callers": [
     "L3F79"
    ],
    "size": 18
   },
   "13546": {
    "name": "L34EA",
    "calls": [
     13559,
     13564
    ],
    "callers": [
     "L3F79"
    ],
    "size": 13
   },
   "13559": {
    "name": "L34F7",
    "calls": [],
    "callers": [
     "L34D8",
     "L34EA"
    ],
    "size": 5
   },
   "13564": {
    "name": "L34FC",
    "calls": [],
    "callers": [
     "L34EA"
    ],
    "size": 5
   },
   "13699": {
    "name": "L3583",
    "calls": [
     17040,
     30592,
     13736,
     17912
    ],
    "callers": [
     "L5A41",
     "L5FD8",
     "boot_build_drivetab",
     "L7491"
    ],
    "size": 37
   },
   "13736": {
    "name": "L35A8",
    "calls": [
     28330
    ],
    "callers": [
     "L3583",
     "L73C2"
    ],
    "size": 26
   },
   "13762": {
    "name": "L35C2",
    "calls": [],
    "callers": [
     "L3ED4"
    ],
    "size": 12
   },
   "13774": {
    "name": "L35CE",
    "calls": [
     17912
    ],
    "callers": [
     "L740C"
    ],
    "size": 11
   },
   "13785": {
    "name": "L35D9",
    "calls": [
     17981
    ],
    "callers": [
     "coldstart_block"
    ],
    "size": 10
   },
   "14035": {
    "name": "L36D3",
    "calls": [
     14224
    ],
    "callers": [
     "sub_ensure_init"
    ],
    "size": 3
   },
   "14038": {
    "name": "L36D6",
    "calls": [],
    "callers": [
     "sub_ensure_init"
    ],
    "size": 5
   },
   "14043": {
    "name": "check_boot_dipsw",
    "calls": [],
    "callers": [
     "sub_ensure_init"
    ],
    "size": 7
   },
   "14050": {
    "name": "sub_ensure_init",
    "calls": [
     14043,
     14080,
     14035,
     14038
    ],
    "callers": [
     "coldstart_block"
    ],
    "size": 30
   },
   "14080": {
    "name": "sub_init_and_count",
    "calls": [
     14281,
     14407
    ],
    "callers": [
     "sub_ensure_init"
    ],
    "size": 34
   },
   "14114": {
    "name": "sub_send_rw_cmd",
    "calls": [
     14281,
     14290
    ],
    "callers": [],
    "size": 24
   },
   "14138": {
    "name": "sub_recv_data",
    "calls": [
     14281,
     14407
    ],
    "callers": [],
    "size": 26
   },
   "14182": {
    "name": "sub_send_data",
    "calls": [
     14290
    ],
    "callers": [],
    "size": 21
   },
   "14224": {
    "name": "sub_check_result",
    "calls": [
     14281,
     14407,
     61041
    ],
    "callers": [
     "L36D3"
    ],
    "size": 57
   },
   "14281": {
    "name": "sub_send_byte",
    "calls": [
     15849
    ],
    "callers": [
     "sub_init_and_count",
     "sub_send_rw_cmd",
     "sub_recv_data",
     "sub_check_result"
    ],
    "size": 9
   },
   "14290": {
    "name": "L37D2",
    "calls": [
     14379
    ],
    "callers": [
     "sub_send_rw_cmd",
     "sub_send_data"
    ],
    "size": 28
   },
   "14375": {
    "name": "L3827",
    "calls": [],
    "callers": [
     "sub_hs_timeout"
    ],
    "size": 4
   },
   "14379": {
    "name": "sub_hs_timeout",
    "calls": [
     14375
    ],
    "callers": [
     "L37D2",
     "sub_recv_byte"
    ],
    "size": 19
   },
   "14407": {
    "name": "sub_recv_byte",
    "calls": [
     14379
    ],
    "callers": [
     "sub_init_and_count",
     "sub_recv_data",
     "sub_check_result"
    ],
    "size": 23
   },
   "14532": {
    "name": "L38C4",
    "calls": [
     14786,
     14820,
     15028
    ],
    "callers": [
     "L77AB"
    ],
    "size": 26
   },
   "14569": {
    "name": "L38E9",
    "calls": [
     15719,
     16976,
     15085,
     14709
    ],
    "callers": [
     "coldstart_block"
    ],
    "size": 54
   },
   "14623": {
    "name": "L391F",
    "calls": [
     15028
    ],
    "callers": [
     "L3AED"
    ],
    "size": 7
   },
   "14690": {
    "name": "L3962",
    "calls": [],
    "callers": [
     "L3D7B"
    ],
    "size": 18
   },
   "14709": {
    "name": "L3975",
    "calls": [
     60918,
     14893,
     15028
    ],
    "callers": [
     "L38E9"
    ],
    "size": 77
   },
   "14786": {
    "name": "L39C2",
    "calls": [],
    "callers": [
     "L38C4"
    ],
    "size": 12
   },
   "14820": {
    "name": "L39E4",
    "calls": [],
    "callers": [
     "L0451",
     "L38C4"
    ],
    "size": 31
   },
   "14893": {
    "name": "L3A2D",
    "calls": [
     15028
    ],
    "callers": [
     "L3975"
    ],
    "size": 7
   },
   "14901": {
    "name": "L3A35",
    "calls": [],
    "callers": [
     "L3AC6"
    ],
    "size": 1
   },
   "14902": {
    "name": "L3A36",
    "calls": [],
    "callers": [
     "L3AC6"
    ],
    "size": 80
   },
   "14991": {
    "name": "L3A8F",
    "calls": [
     24
    ],
    "callers": [
     "L5550"
    ],
    "size": 23
   },
   "15014": {
    "name": "L3AA6",
    "calls": [],
    "callers": [
     "L043D"
    ],
    "size": 4
   },
   "15028": {
    "name": "oscall_dispatch_3b",
    "calls": [
     15046
    ],
    "callers": [
     "L38C4",
     "L391F",
     "L3975",
     "L3A2D",
     "L3D67"
    ],
    "size": 10
   },
   "15038": {
    "name": "oscall_dispatch_2b",
    "calls": [],
    "callers": [],
    "size": 8
   },
   "15046": {
    "name": "L3AC6",
    "calls": [
     14901,
     14902
    ],
    "callers": [
     "oscall_dispatch_3b"
    ],
    "size": 38
   },
   "15085": {
    "name": "L3AED",
    "calls": [
     14623
    ],
    "callers": [
     "L38E9"
    ],
    "size": 10
   },
   "15313": {
    "name": "L3BD1",
    "calls": [
     15347
    ],
    "callers": [
     "L3BE5"
    ],
    "size": 6
   },
   "15333": {
    "name": "L3BE5",
    "calls": [
     15347,
     15313
    ],
    "callers": [
     "L0000"
    ],
    "size": 7
   },
   "15347": {
    "name": "L3BF3",
    "calls": [
     15739,
     15729,
     15726
    ],
    "callers": [
     "L3BD1",
     "L3BE5"
    ],
    "size": 13
   },
   "15552": {
    "name": "install_ram_hooks",
    "calls": [
     15764
    ],
    "callers": [],
    "size": 63
   },
   "15719": {
    "name": "L3D67",
    "calls": [
     15028
    ],
    "callers": [
     "L38E9"
    ],
    "size": 7
   },
   "15726": {
    "name": "L3D6E",
    "calls": [],
    "callers": [
     "L3BF3"
    ],
    "size": 5
   },
   "15729": {
    "name": "L3D71",
    "calls": [],
    "callers": [
     "L3BF3"
    ],
    "size": 4
   },
   "15733": {
    "name": "L3D75",
    "calls": [
     1085,
     30711
    ],
    "callers": [
     "L3D7B"
    ],
    "size": 6
   },
   "15739": {
    "name": "L3D7B",
    "calls": [
     14690,
     15733
    ],
    "callers": [
     "L3BF3"
    ],
    "size": 17
   },
   "15764": {
    "name": "L3D94",
    "calls": [],
    "callers": [
     "install_ram_hooks"
    ],
    "size": 16
   },
   "15806": {
    "name": "bank_restore_32_71",
    "calls": [],
    "callers": [],
    "size": 13
   },
   "15849": {
    "name": "L3DE9",
    "calls": [
     60927
    ],
    "callers": [
     "sub_send_byte"
    ],
    "size": 36
   },
   "16084": {
    "name": "L3ED4",
    "calls": [
     13762
    ],
    "callers": [
     "L3EF3",
     "L3F27",
     "L5986",
     "L7755",
     "L7780"
    ],
    "size": 31
   },
   "16115": {
    "name": "L3EF3",
    "calls": [
     16084,
     16167
    ],
    "callers": [
     "L5989"
    ],
    "size": 52
   },
   "16167": {
    "name": "L3F27",
    "calls": [
     16084
    ],
    "callers": [
     "L3EF3"
    ],
    "size": 10
   },
   "16249": {
    "name": "L3F79",
    "calls": [
     16417,
     16389,
     13528,
     17546,
     13546
    ],
    "callers": [
     "L5F0E"
    ],
    "size": 114
   },
   "16389": {
    "name": "L4005",
    "calls": [
     17546
    ],
    "callers": [
     "L3F79"
    ],
    "size": 14
   },
   "16405": {
    "name": "L4015",
    "calls": [],
    "callers": [
     "L5F92"
    ],
    "size": 12
   },
   "16417": {
    "name": "L4021",
    "calls": [
     17182,
     16437,
     17129
    ],
    "callers": [
     "L3F79"
    ],
    "size": 20
   },
   "16437": {
    "name": "L4035",
    "calls": [
     17086
    ],
    "callers": [
     "L4021"
    ],
    "size": 18
   },
   "16970": {
    "name": "L424A",
    "calls": [],
    "callers": [
     "L4250"
    ],
    "size": 6
   },
   "16976": {
    "name": "L4250",
    "calls": [
     16970
    ],
    "callers": [
     "L38E9"
    ],
    "size": 7
   },
   "17035": {
    "name": "L428B",
    "calls": [
     17048
    ],
    "callers": [
     "L75AA"
    ],
    "size": 5
   },
   "17040": {
    "name": "L4290",
    "calls": [],
    "callers": [
     "L3583",
     "L73C2"
    ],
    "size": 8
   },
   "17048": {
    "name": "L4298",
    "calls": [],
    "callers": [
     "L428B"
    ],
    "size": 5
   },
   "17053": {
    "name": "L429D",
    "calls": [
     17182
    ],
    "callers": [
     "L448A",
     "L4494",
     "L6528",
     "L654D"
    ],
    "size": 23
   },
   "17076": {
    "name": "L42B4",
    "calls": [],
    "callers": [
     "L5F0E"
    ],
    "size": 10
   },
   "17086": {
    "name": "L42BE",
    "calls": [],
    "callers": [
     "L4035"
    ],
    "size": 22
   },
   "17129": {
    "name": "L42E9",
    "calls": [],
    "callers": [
     "L4021",
     "L5F0E"
    ],
    "size": 16
   },
   "17182": {
    "name": "L431E",
    "calls": [
     2822,
     17203
    ],
    "callers": [
     "L4021",
     "L429D",
     "L5F0E"
    ],
    "size": 21
   },
   "17203": {
    "name": "L4333",
    "calls": [],
    "callers": [
     "L431E"
    ],
    "size": 12
   },
   "17215": {
    "name": "L433F",
    "calls": [],
    "callers": [
     "L6FD1"
    ],
    "size": 13
   },
   "17232": {
    "name": "L4350",
    "calls": [
     17442,
     20955
    ],
    "callers": [
     "L448A",
     "L654D"
    ],
    "size": 124
   },
   "17408": {
    "name": "L4400",
    "calls": [],
    "callers": [
     "L51DB"
    ],
    "size": 27
   },
   "17442": {
    "name": "L4422",
    "calls": [],
    "callers": [
     "L4350",
     "L4452"
    ],
    "size": 48
   },
   "17490": {
    "name": "L4452",
    "calls": [
     17442
    ],
    "callers": [
     "L6528"
    ],
    "size": 9
   },
   "17546": {
    "name": "L448A",
    "calls": [
     17053,
     17232
    ],
    "callers": [
     "L3F79",
     "L4005"
    ],
    "size": 7
   },
   "17556": {
    "name": "L4494",
    "calls": [
     17053
    ],
    "callers": [
     "L5E49",
     "L6568"
    ],
    "size": 11
   },
   "17567": {
    "name": "L449F",
    "calls": [],
    "callers": [
     "L5A58"
    ],
    "size": 5
   },
   "17572": {
    "name": "L44A4",
    "calls": [
     60894
    ],
    "callers": [
     "L0605",
     "L0B0B",
     "L1BBB",
     "L44E3",
     "L4F21",
     "L4FB4",
     "L50A5",
     "L53F6",
     "L5441",
     "L6568"
    ],
    "size": 15
   },
   "17587": {
    "name": "L44B3",
    "calls": [
     60897,
     17621
    ],
    "callers": [
     "L1BBB",
     "L44C2"
    ],
    "size": 15
   },
   "17602": {
    "name": "L44C2",
    "calls": [
     60900,
     17587
    ],
    "callers": [
     "L0605"
    ],
    "size": 19
   },
   "17621": {
    "name": "L44D5",
    "calls": [],
    "callers": [
     "L03B3",
     "L0996",
     "L0B0B",
     "L1BBB",
     "L44B3",
     "L44E3",
     "L4F21",
     "L50A5",
     "L50CD",
     "L53F6",
     "L5441",
     "L6568"
    ],
    "size": 14
   },
   "17635": {
    "name": "L44E3",
    "calls": [
     17621,
     17572
    ],
    "callers": [
     "L0605",
     "L0996"
    ],
    "size": 14
   },
   "17745": {
    "name": "veccall_enter",
    "calls": [
     60915
    ],
    "callers": [
     "L6EAA",
     "L6EB6",
     "boot_negotiate",
     "boot_build_drivetab"
    ],
    "size": 48
   },
   "17793": {
    "name": "veccall_restore_a71",
    "calls": [],
    "callers": [],
    "size": 14
   },
   "17912": {
    "name": "L45F8",
    "calls": [
     18038
    ],
    "callers": [
     "L3583",
     "L35CE"
    ],
    "size": 35
   },
   "17981": {
    "name": "L463D",
    "calls": [
     18048
    ],
    "callers": [
     "L35D9",
     "L7DA6"
    ],
    "size": 17
   },
   "18005": {
    "name": "L4655",
    "calls": [
     18038
    ],
    "callers": [
     "L7570"
    ],
    "size": 18
   },
   "18038": {
    "name": "L4676",
    "calls": [
     18048
    ],
    "callers": [
     "L45F8",
     "L4655"
    ],
    "size": 10
   },
   "18048": {
    "name": "L4680",
    "calls": [],
    "callers": [
     "L463D",
     "L4676"
    ],
    "size": 12
   },
   "18168": {
    "name": "L46F8",
    "calls": [
     19890,
     60849,
     19893
    ],
    "callers": [
     "L4735",
     "L481D"
    ],
    "size": 44
   },
   "18229": {
    "name": "L4735",
    "calls": [
     18168,
     19884,
     60927
    ],
    "callers": [
     "L59AC",
     "L740C",
     "L75DA"
    ],
    "size": 13
   },
   "18461": {
    "name": "L481D",
    "calls": [
     19485,
     18168,
     20108,
     60783,
     19893
    ],
    "callers": [
     "L4C70",
     "L4CAB",
     "L7497"
    ],
    "size": 32
   },
   "19159": {
    "name": "L4AD7",
    "calls": [],
    "callers": [
     "L4B0C"
    ],
    "size": 12
   },
   "19212": {
    "name": "L4B0C",
    "calls": [
     19159
    ],
    "callers": [
     "L4F21",
     "L50CD"
    ],
    "size": 14
   },
   "19282": {
    "name": "L4B52",
    "calls": [],
    "callers": [
     "L5925"
    ],
    "size": 2
   },
   "19284": {
    "name": "L4B54",
    "calls": [
     19302,
     60648,
     19872
    ],
    "callers": [
     "L59AC",
     "L740C"
    ],
    "size": 18
   },
   "19302": {
    "name": "L4B66",
    "calls": [
     19501,
     20108
    ],
    "callers": [
     "L4B54",
     "L4B7B"
    ],
    "size": 21
   },
   "19323": {
    "name": "L4B7B",
    "calls": [
     19302,
     60654,
     19872
    ],
    "callers": [
     "L5A08",
     "L73C2",
     "L7563"
    ],
    "size": 17
   },
   "19340": {
    "name": "L4B8C",
    "calls": [],
    "callers": [
     "boot_build_drivetab"
    ],
    "size": 29
   },
   "19485": {
    "name": "L4C1D",
    "calls": [],
    "callers": [
     "L481D"
    ],
    "size": 2
   },
   "19501": {
    "name": "L4C2D",
    "calls": [],
    "callers": [
     "L4B66"
    ],
    "size": 2
   },
   "19568": {
    "name": "L4C70",
    "calls": [
     21362,
     2533,
     18461,
     19878
    ],
    "callers": [
     "L75AA"
    ],
    "size": 13
   },
   "19627": {
    "name": "L4CAB",
    "calls": [
     18461
    ],
    "callers": [
     "L047A",
     "L5A08"
    ],
    "size": 8
   },
   "19872": {
    "name": "L4DA0",
    "calls": [],
    "callers": [
     "L4B54",
     "L4B7B"
    ],
    "size": 8
   },
   "19878": {
    "name": "L4DA6",
    "calls": [],
    "callers": [
     "L4C70"
    ],
    "size": 8
   },
   "19884": {
    "name": "L4DAC",
    "calls": [],
    "callers": [
     "L4735"
    ],
    "size": 8
   },
   "19890": {
    "name": "L4DB2",
    "calls": [],
    "callers": [
     "L46F8"
    ],
    "size": 5
   },
   "19893": {
    "name": "L4DB5",
    "calls": [
     60609,
     947
    ],
    "callers": [
     "L46F8",
     "L481D"
    ],
    "size": 33
   },
   "20108": {
    "name": "L4E8C",
    "calls": [
     60672,
     60675
    ],
    "callers": [
     "L481D",
     "L4B66"
    ],
    "size": 39
   },
   "20161": {
    "name": "L4EC1",
    "calls": [
     947
    ],
    "callers": [
     "L11D3"
    ],
    "size": 35
   },
   "20257": {
    "name": "L4F21",
    "calls": [
     60822,
     17572,
     2822,
     60804,
     17621,
     20549,
     60882,
     60813,
     8439,
     20645,
     19212
    ],
    "callers": [
     "L5A08"
    ],
    "size": 147
   },
   "20404": {
    "name": "L4FB4",
    "calls": [
     60786,
     7636,
     22921,
     3979,
     17572
    ],
    "callers": [
     "L03F3"
    ],
    "size": 49
   },
   "20469": {
    "name": "L4FF5",
    "calls": [],
    "callers": [
     "L5F92"
    ],
    "size": 19
   },
   "20549": {
    "name": "L5045",
    "calls": [],
    "callers": [
     "L4F21"
    ],
    "size": 20
   },
   "20569": {
    "name": "L5059",
    "calls": [],
    "callers": [
     "L0996"
    ],
    "size": 41
   },
   "20645": {
    "name": "L50A5",
    "calls": [
     2827,
     17621,
     1541,
     3132,
     17572
    ],
    "callers": [
     "L4F21"
    ],
    "size": 37
   },
   "20685": {
    "name": "L50CD",
    "calls": [
     19212,
     17621
    ],
    "callers": [
     "L5A86"
    ],
    "size": 46
   },
   "20731": {
    "name": "L50FB",
    "calls": [
     30168,
     22921,
     23128,
     1119,
     1146
    ],
    "callers": [
     "L0375"
    ],
    "size": 46
   },
   "20777": {
    "name": "L5129",
    "calls": [],
    "callers": [
     "L5A44"
    ],
    "size": 2
   },
   "20779": {
    "name": "L512B",
    "calls": [
     24,
     23145
    ],
    "callers": [
     "L5A86"
    ],
    "size": 21
   },
   "20955": {
    "name": "L51DB",
    "calls": [
     17408
    ],
    "callers": [
     "L4350"
    ],
    "size": 9
   },
   "20964": {
    "name": "L51E4",
    "calls": [
     28522
    ],
    "callers": [
     "L69E1"
    ],
    "size": 7
   },
   "21013": {
    "name": "L5215",
    "calls": [],
    "callers": [
     "L5ACA"
    ],
    "size": 1
   },
   "21014": {
    "name": "L5216",
    "calls": [],
    "callers": [
     "L1AB4",
     "L53AF",
     "L5480",
     "L5ACA"
    ],
    "size": 7
   },
   "21362": {
    "name": "L5372",
    "calls": [
     60825
    ],
    "callers": [
     "L4C70",
     "L5925",
     "L5A08",
     "L5A72",
     "L60D8"
    ],
    "size": 11
   },
   "21373": {
    "name": "L537D",
    "calls": [
     32,
     21617
    ],
    "callers": [
     "L53D2",
     "L5441"
    ],
    "size": 42
   },
   "21423": {
    "name": "L53AF",
    "calls": [
     21014
    ],
    "callers": [
     "L53D2",
     "L5441"
    ],
    "size": 28
   },
   "21458": {
    "name": "L53D2",
    "calls": [
     21423,
     21373,
     1744,
     21625
    ],
    "callers": [
     "L53F6"
    ],
    "size": 36
   },
   "21494": {
    "name": "L53F6",
    "calls": [
     60903,
     17572,
     17621,
     16,
     21458
    ],
    "callers": [
     "L5441"
    ],
    "size": 75
   },
   "21569": {
    "name": "L5441",
    "calls": [
     17621,
     60906,
     21494,
     17572,
     16,
     21423,
     21373,
     921
    ],
    "callers": [
     "L0B34"
    ],
    "size": 48
   },
   "21617": {
    "name": "L5471",
    "calls": [],
    "callers": [
     "L537D"
    ],
    "size": 8
   },
   "21625": {
    "name": "L5479",
    "calls": [],
    "callers": [
     "L53D2"
    ],
    "size": 7
   },
   "21632": {
    "name": "L5480",
    "calls": [
     21014
    ],
    "callers": [
     "L09E5"
    ],
    "size": 20
   },
   "21720": {
    "name": "L54D8",
    "calls": [
     21874,
     21745,
     22208
    ],
    "callers": [
     "L0C9C",
     "L585A"
    ],
    "size": 20
   },
   "21745": {
    "name": "L54F1",
    "calls": [],
    "callers": [
     "L54D8",
     "L54FC"
    ],
    "size": 11
   },
   "21756": {
    "name": "L54FC",
    "calls": [
     2573,
     21745,
     8444,
     32,
     947
    ],
    "callers": [
     "L5550"
    ],
    "size": 83
   },
   "21840": {
    "name": "L5550",
    "calls": [
     21756,
     22220,
     8429,
     14991,
     23154
    ],
    "callers": [
     "L047A",
     "L1BBB",
     "L28BA"
    ],
    "size": 30
   },
   "21874": {
    "name": "L5572",
    "calls": [
     32,
     21901
    ],
    "callers": [
     "L54D8"
    ],
    "size": 25
   },
   "21899": {
    "name": "L558B",
    "calls": [],
    "callers": [
     "L59A5",
     "L59AC"
    ],
    "size": 2
   },
   "22144": {
    "name": "L5680",
    "calls": [
     4944,
     8790,
     947,
     21742,
     22224,
     22223,
     22200,
     21804
    ],
    "callers": [
     "L11D3"
    ],
    "size": 56
   },
   "22208": {
    "name": "L56C0",
    "calls": [],
    "callers": [
     "L54D8"
    ],
    "size": 9
   },
   "22217": {
    "name": "L56C9",
    "calls": [
     8790
    ],
    "callers": [
     "L585A"
    ],
    "size": 3
   },
   "22220": {
    "name": "L56CC",
    "calls": [
     22247,
     32
    ],
    "callers": [
     "L5550"
    ],
    "size": 27
   },
   "22247": {
    "name": "L56E7",
    "calls": [
     60690,
     32
    ],
    "callers": [
     "L0C9C",
     "L56CC"
    ],
    "size": 17
   },
   "22570": {
    "name": "L582A",
    "calls": [],
    "callers": [
     "L585A"
    ],
    "size": 31
   },
   "22618": {
    "name": "L585A",
    "calls": [
     8,
     22570,
     52570,
     32,
     21720,
     8444,
     6307,
     2822,
     22742,
     4558,
     22217
    ],
    "callers": [
     "L17C9"
    ],
    "size": 124
   },
   "22742": {
    "name": "L58D6",
    "calls": [
     8,
     6307
    ],
    "callers": [
     "L585A"
    ],
    "size": 14
   },
   "22821": {
    "name": "L5925",
    "calls": [
     21362,
     19282,
     22949,
     22918
    ],
    "callers": [
     "L0018"
    ],
    "size": 34
   },
   "22918": {
    "name": "L5986",
    "calls": [
     16084
    ],
    "callers": [
     "L5925",
     "L5989"
    ],
    "size": 3
   },
   "22921": {
    "name": "L5989",
    "calls": [
     16115,
     22918
    ],
    "callers": [
     "L047A",
     "L4FB4",
     "L50FB"
    ],
    "size": 27
   },
   "22949": {
    "name": "L59A5",
    "calls": [
     21899
    ],
    "callers": [
     "L5925"
    ],
    "size": 7
   },
   "22956": {
    "name": "L59AC",
    "calls": [
     21899,
     18229,
     19284
    ],
    "callers": [
     "L73FF"
    ],
    "size": 36
   },
   "23048": {
    "name": "L5A08",
    "calls": [
     60687,
     21362,
     23105,
     19323,
     19627,
     20257
    ],
    "callers": [
     "L60D8"
    ],
    "size": 42
   },
   "23105": {
    "name": "L5A41",
    "calls": [
     13699
    ],
    "callers": [
     "L5A08",
     "L5A86"
    ],
    "size": 3
   },
   "23108": {
    "name": "L5A44",
    "calls": [
     20777
    ],
    "callers": [
     "L5A86"
    ],
    "size": 20
   },
   "23128": {
    "name": "L5A58",
    "calls": [
     17567,
     23145
    ],
    "callers": [
     "L047A",
     "L1BBB",
     "L50FB"
    ],
    "size": 7
   },
   "23145": {
    "name": "L5A69",
    "calls": [
     60684,
     24
    ],
    "callers": [
     "L512B",
     "L5A58",
     "L6568"
    ],
    "size": 9
   },
   "23154": {
    "name": "L5A72",
    "calls": [
     21362
    ],
    "callers": [
     "L5550"
    ],
    "size": 7
   },
   "23174": {
    "name": "L5A86",
    "calls": [
     60810,
     23105,
     23108,
     20779,
     20685
    ],
    "callers": [
     "L0996"
    ],
    "size": 29
   },
   "23242": {
    "name": "L5ACA",
    "calls": [
     60819,
     21013,
     915,
     21014,
     16
    ],
    "callers": [
     "L0C9C"
    ],
    "size": 238
   },
   "24137": {
    "name": "L5E49",
    "calls": [
     17556
    ],
    "callers": [
     "L5F0E",
     "L6F6A"
    ],
    "size": 11
   },
   "24334": {
    "name": "L5F0E",
    "calls": [
     17076,
     17182,
     17129,
     16249,
     24137
    ],
    "callers": [
     "L6568",
     "L6F6A"
    ],
    "size": 66
   },
   "24438": {
    "name": "L5F76",
    "calls": [],
    "callers": [
     "L6347",
     "L63E5"
    ],
    "size": 16
   },
   "24454": {
    "name": "L5F86",
    "calls": [],
    "callers": [
     "L5FD8",
     "L6568"
    ],
    "size": 12
   },
   "24466": {
    "name": "L5F92",
    "calls": [
     60696,
     24792,
     16405,
     20469
    ],
    "callers": [
     "L04A7"
    ],
    "size": 42
   },
   "24508": {
    "name": "L5FBC",
    "calls": [
     24536
    ],
    "callers": [
     "L6144"
    ],
    "size": 6
   },
   "24520": {
    "name": "L5FC8",
    "calls": [
     60693,
     24792,
     24900
    ],
    "callers": [
     "L740C"
    ],
    "size": 16
   },
   "24536": {
    "name": "L5FD8",
    "calls": [
     25896,
     24454,
     13699,
     24650,
     24
    ],
    "callers": [
     "L5FBC",
     "L6144"
    ],
    "size": 84
   },
   "24642": {
    "name": "L6042",
    "calls": [],
    "callers": [
     "L604A",
     "L605B"
    ],
    "size": 8
   },
   "24650": {
    "name": "L604A",
    "calls": [
     24642,
     24667
    ],
    "callers": [
     "L5FD8"
    ],
    "size": 12
   },
   "24662": {
    "name": "L6056",
    "calls": [],
    "callers": [
     "L0106"
    ],
    "size": 5
   },
   "24667": {
    "name": "L605B",
    "calls": [
     24642
    ],
    "callers": [
     "L604A"
    ],
    "size": 31
   },
   "24792": {
    "name": "L60D8",
    "calls": [
     21362,
     23048
    ],
    "callers": [
     "L5F92",
     "L5FC8"
    ],
    "size": 67
   },
   "24900": {
    "name": "L6144",
    "calls": [
     24536,
     24508
    ],
    "callers": [
     "L5FC8"
    ],
    "size": 12
   },
   "25415": {
    "name": "L6347",
    "calls": [
     25933,
     24438
    ],
    "callers": [
     "L7403",
     "L7583"
    ],
    "size": 26
   },
   "25573": {
    "name": "L63E5",
    "calls": [
     24438
    ],
    "callers": [
     "L6568"
    ],
    "size": 13
   },
   "25896": {
    "name": "L6528",
    "calls": [
     17053,
     17490
    ],
    "callers": [
     "L5FD8"
    ],
    "size": 24
   },
   "25933": {
    "name": "L654D",
    "calls": [
     17053,
     17232
    ],
    "callers": [
     "L6347"
    ],
    "size": 16
   },
   "25960": {
    "name": "L6568",
    "calls": [
     2827,
     2822,
     24334,
     1541,
     3132,
     17621,
     7297,
     17572,
     23145,
     10434,
     24,
     6476,
     6451,
     24454,
     25573,
     17556,
     1191
    ],
    "callers": [
     "L047A"
    ],
    "size": 180
   },
   "26140": {
    "name": "L661C",
    "calls": [
     24
    ],
    "callers": [
     "L1933"
    ],
    "size": 31
   },
   "27089": {
    "name": "L69D1",
    "calls": [],
    "callers": [
     "coldstart_block"
    ],
    "size": 16
   },
   "27105": {
    "name": "L69E1",
    "calls": [
     20964
    ],
    "callers": [
     "coldstart_block"
    ],
    "size": 29
   },
   "28328": {
    "name": "L6EA8",
    "calls": [],
    "callers": [
     "L6EB6"
    ],
    "size": 2
   },
   "28330": {
    "name": "L6EAA",
    "calls": [
     17745
    ],
    "callers": [
     "L35A8"
    ],
    "size": 12
   },
   "28342": {
    "name": "L6EB6",
    "calls": [
     17745,
     28328
    ],
    "callers": [
     "coldstart_block"
    ],
    "size": 69
   },
   "28422": {
    "name": "boot_negotiate",
    "calls": [
     17745
    ],
    "callers": [
     "coldstart_block"
    ],
    "size": 4
   },
   "28426": {
    "name": "boot_build_drivetab",
    "calls": [
     17745,
     13699,
     19340
    ],
    "callers": [],
    "size": 20
   },
   "28522": {
    "name": "L6F6A",
    "calls": [
     28596,
     6272,
     28625,
     24334,
     24137
    ],
    "callers": [
     "L51E4"
    ],
    "size": 63
   },
   "28596": {
    "name": "L6FB4",
    "calls": [],
    "callers": [
     "L6F6A"
    ],
    "size": 29
   },
   "28625": {
    "name": "L6FD1",
    "calls": [
     17215
    ],
    "callers": [
     "L6F6A"
    ],
    "size": 138
   },
   "29389": {
    "name": "coldstart_block",
    "calls": [
     13785,
     27089,
     27105,
     14050,
     28422,
     28342,
     14569,
     60807
    ],
    "callers": [
     "boot_stop_key_fork"
    ],
    "size": 117
   },
   "29634": {
    "name": "L73C2",
    "calls": [
     17040,
     30592,
     13736,
     30064,
     29708,
     19323,
     29898,
     30083,
     29699
    ],
    "callers": [
     "L7403",
     "L740C",
     "L74C4",
     "L74CA"
    ],
    "size": 61
   },
   "29695": {
    "name": "L73FF",
    "calls": [
     22956
    ],
    "callers": [
     "L7583"
    ],
    "size": 4
   },
   "29699": {
    "name": "L7403",
    "calls": [
     25415,
     29634
    ],
    "callers": [
     "L73C2",
     "L74CA"
    ],
    "size": 9
   },
   "29708": {
    "name": "L740C",
    "calls": [
     29634,
     13774,
     29846,
     24520,
     29847,
     18229,
     19284
    ],
    "callers": [
     "L73C2"
    ],
    "size": 73
   },
   "29841": {
    "name": "L7491",
    "calls": [
     13699,
     29847
    ],
    "callers": [
     "L7570"
    ],
    "size": 5
   },
   "29846": {
    "name": "L7496",
    "calls": [],
    "callers": [
     "L740C"
    ],
    "size": 1
   },
   "29847": {
    "name": "L7497",
    "calls": [
     18461,
     30315,
     2454
    ],
    "callers": [
     "L740C",
     "L7491"
    ],
    "size": 40
   },
   "29892": {
    "name": "L74C4",
    "calls": [
     29634
    ],
    "callers": [
     "L7583",
     "L75DA"
    ],
    "size": 3
   },
   "29898": {
    "name": "L74CA",
    "calls": [
     30051,
     30083,
     29699,
     30122,
     29634
    ],
    "callers": [
     "L73C2"
    ],
    "size": 69
   },
   "30051": {
    "name": "L7563",
    "calls": [
     30064,
     19323
    ],
    "callers": [
     "L74CA",
     "L75AA"
    ],
    "size": 13
   },
   "30064": {
    "name": "L7570",
    "calls": [
     29841,
     18005
    ],
    "callers": [
     "L73C2",
     "L7563"
    ],
    "size": 19
   },
   "30083": {
    "name": "L7583",
    "calls": [
     25415,
     29695,
     29892
    ],
    "callers": [
     "L73C2",
     "L74CA"
    ],
    "size": 39
   },
   "30122": {
    "name": "L75AA",
    "calls": [
     30051,
     1586,
     17035,
     19568
    ],
    "callers": [
     "L74CA"
    ],
    "size": 46
   },
   "30168": {
    "name": "L75D8",
    "calls": [],
    "callers": [
     "L50FB"
    ],
    "size": 2
   },
   "30170": {
    "name": "L75DA",
    "calls": [
     18229,
     29892
    ],
    "callers": [
     "L047A"
    ],
    "size": 26
   },
   "30315": {
    "name": "L766B",
    "calls": [],
    "callers": [
     "L7497"
    ],
    "size": 7
   },
   "30419": {
    "name": "L76D3",
    "calls": [
     32
    ],
    "callers": [
     "L7716"
    ],
    "size": 10
   },
   "30486": {
    "name": "L7716",
    "calls": [
     30419,
     30572,
     30586,
     30521,
     30549
    ],
    "callers": [
     "L7780"
    ],
    "size": 35
   },
   "30521": {
    "name": "L7739",
    "calls": [
     30535
    ],
    "callers": [
     "L7716"
    ],
    "size": 14
   },
   "30535": {
    "name": "L7747",
    "calls": [],
    "callers": [
     "L7739",
     "L7755"
    ],
    "size": 14
   },
   "30549": {
    "name": "L7755",
    "calls": [
     30535,
     16084
    ],
    "callers": [
     "L7716"
    ],
    "size": 23
   },
   "30572": {
    "name": "L776C",
    "calls": [
     32
    ],
    "callers": [
     "L7716"
    ],
    "size": 14
   },
   "30586": {
    "name": "L777A",
    "calls": [
     32
    ],
    "callers": [
     "L7716"
    ],
    "size": 6
   },
   "30592": {
    "name": "L7780",
    "calls": [
     16084,
     30486
    ],
    "callers": [
     "L3583",
     "L73C2"
    ],
    "size": 28
   },
   "30635": {
    "name": "L77AB",
    "calls": [
     14532,
     61648
    ],
    "callers": [
     "boot_stop_key_fork"
    ],
    "size": 27
   },
   "30711": {
    "name": "L77F7",
    "calls": [],
    "callers": [
     "L045F",
     "L3D75"
    ],
    "size": 19
   },
   "30730": {
    "name": "boot_stop_key_fork",
    "calls": [
     30635,
     29389,
     879
    ],
    "callers": [],
    "size": 22
   },
   "31949": {
    "name": "L7CCD",
    "calls": [
     947
    ],
    "callers": [
     "L04A7",
     "L0996"
    ],
    "size": 9
   },
   "32166": {
    "name": "L7DA6",
    "calls": [
     17981
    ],
    "callers": [
     "L7F15"
    ],
    "size": 29
   },
   "32533": {
    "name": "L7F15",
    "calls": [
     32166,
     32547
    ],
    "callers": [
     "L0F8B"
    ],
    "size": 5
   },
   "32538": {
    "name": "L7F1A",
    "calls": [
     32641
    ],
    "callers": [
     "L0F8B"
    ],
    "size": 9
   },
   "32547": {
    "name": "L7F23",
    "calls": [],
    "callers": [
     "L7F15"
    ],
    "size": 13
   },
   "32620": {
    "name": "L7F6C",
    "calls": [],
    "callers": [
     "L7F81"
    ],
    "size": 15
   },
   "32641": {
    "name": "L7F81",
    "calls": [
     32620
    ],
    "callers": [
     "L7F1A"
    ],
    "size": 6
   }
  },
  "vars": {
   "54757": {
    "r": [],
    "w": [
     "L585A"
    ]
   },
   "58953": {
    "r": [
     "L047A"
    ],
    "w": [
     "L6568"
    ]
   },
   "58955": {
    "r": [
     "L5925",
     "L5989"
    ],
    "w": [
     "L5925",
     "L5989"
    ]
   },
   "58956": {
    "r": [
     "L5925",
     "L661C"
    ],
    "w": [
     "L0F8B",
     "L512B",
     "L5989"
    ]
   },
   "58959": {
    "r": [],
    "w": [
     "L1880",
     "L51E4"
    ]
   },
   "58960": {
    "r": [],
    "w": [
     "L1880"
    ]
   },
   "58962": {
    "r": [
     "L59A5",
     "L5A44"
    ],
    "w": [
     "L047A",
     "L50FB",
     "L512B",
     "L5A44"
    ]
   },
   "58963": {
    "r": [],
    "w": [
     "L03B3",
     "L4DB5"
    ]
   },
   "58964": {
    "r": [
     "L4EC1",
     "L4F21"
    ],
    "w": []
   },
   "58966": {
    "r": [
     "L0375",
     "L03B3",
     "L5059",
     "L50CD",
     "L50FB"
    ],
    "w": [
     "L04A7",
     "L0996"
    ]
   },
   "58968": {
    "r": [
     "L0605",
     "L1BBB",
     "L4F21",
     "L50A5",
     "L53F6"
    ],
    "w": []
   },
   "59039": {
    "r": [
     "L047A",
     "L3F79",
     "L4F21",
     "L50FB",
     "L5FD8",
     "L60D8",
     "L6144"
    ],
    "w": [
     "L7497",
     "L75DA"
    ]
   },
   "59040": {
    "r": [
     "L59AC",
     "L60D8"
    ],
    "w": [
     "L03B3",
     "L7497",
     "L75AA",
     "L75DA"
    ]
   },
   "59041": {
    "r": [],
    "w": [
     "L740C"
    ]
   },
   "59042": {
    "r": [],
    "w": [
     "L7497"
    ]
   },
   "59045": {
    "r": [
     "L7780"
    ],
    "w": [
     "L7780"
    ]
   },
   "59047": {
    "r": [
     "L3583",
     "L4290",
     "L73C2"
    ],
    "w": []
   },
   "59048": {
    "r": [],
    "w": [
     "L4298"
    ]
   },
   "59049": {
    "r": [
     "L0F8B"
    ],
    "w": [
     "L0F8B"
    ]
   },
   "59051": {
    "r": [
     "L0B0B"
    ],
    "w": [
     "L03B3",
     "L6568"
    ]
   },
   "59053": {
    "r": [],
    "w": [
     "L03B3",
     "L6056",
     "L6568"
    ]
   },
   "59056": {
    "r": [
     "L5E49",
     "L5F0E",
     "L63E5",
     "L6F6A",
     "L6FB4",
     "L7583"
    ],
    "w": [
     "L6F6A",
     "L6FB4",
     "L7583"
    ]
   },
   "59058": {
    "r": [
     "L6F6A"
    ],
    "w": []
   },
   "59060": {
    "r": [
     "L4035",
     "L42BE",
     "L654D"
    ],
    "w": [
     "L4035"
    ]
   },
   "59061": {
    "r": [
     "L6347"
    ],
    "w": []
   },
   "59062": {
    "r": [],
    "w": [
     "L7497"
    ]
   },
   "59064": {
    "r": [
     "L3F79",
     "L6FB4"
    ],
    "w": []
   },
   "59065": {
    "r": [
     "L6FD1"
    ],
    "w": []
   },
   "59067": {
    "r": [],
    "w": [
     "L6568"
    ]
   },
   "59069": {
    "r": [],
    "w": [
     "L6568"
    ]
   },
   "59072": {
    "r": [
     "L6FD1",
     "coldstart_block",
     "L7F1A",
     "L7F23"
    ],
    "w": [
     "L6FD1",
     "L7F23"
    ],
    "known": {
     "name": "shadow_port30",
     "ja": "port 30h(書込専用)のシャドウ",
     "en": "shadow of write-only port 30h"
    }
   },
   "59073": {
    "r": [
     "L3ED4",
     "L6FD1",
     "coldstart_block"
    ],
    "w": [
     "L6FD1"
    ],
    "known": {
     "name": "shadow_port40",
     "ja": "port 40h出力のシャドウ",
     "en": "shadow of port 40h output"
    }
   },
   "59074": {
    "r": [
     "L6FD1",
     "coldstart_block",
     "L77AB"
    ],
    "w": [
     "L6FD1"
    ],
    "known": {
     "name": "shadow_port31",
     "ja": "port 31h(書込専用)のシャドウ",
     "en": "shadow of write-only port 31h"
    }
   },
   "59075": {
    "r": [],
    "w": [
     "coldstart_block"
    ]
   },
   "59076": {
    "r": [
     "L42B4",
     "L42E9",
     "L431E",
     "L4422",
     "L6FD1"
    ],
    "w": []
   },
   "59078": {
    "r": [],
    "w": [
     "L5F92"
    ]
   },
   "59081": {
    "r": [
     "L04A7",
     "L0996"
    ],
    "w": [
     "L7CCD"
    ]
   },
   "59082": {
    "r": [
     "L3583",
     "L35C2",
     "L3EF3",
     "L5A86",
     "L740C",
     "L7570"
    ],
    "w": [
     "L3583",
     "L3EF3",
     "L7497"
    ]
   },
   "59083": {
    "r": [
     "L4680"
    ],
    "w": []
   },
   "59085": {
    "r": [],
    "w": [
     "L3F79",
     "L7497",
     "L75DA"
    ]
   },
   "59086": {
    "r": [
     "L34EA"
    ],
    "w": [
     "L34F7"
    ]
   },
   "59113": {
    "r": [
     "L3EF3"
    ],
    "w": [
     "L3EF3"
    ]
   },
   "59117": {
    "r": [],
    "w": [
     "L7DA6"
    ]
   },
   "59118": {
    "r": [
     "L5045",
     "L5059"
    ],
    "w": []
   },
   "59119": {
    "r": [
     "L4015",
     "L5045",
     "L5059"
    ],
    "w": []
   },
   "59121": {
    "r": [
     "L0996"
    ],
    "w": [
     "L5045"
    ]
   },
   "59368": {
    "r": [],
    "w": [],
    "known": {
     "name": "basic_area_ptr",
     "ja": "BASICエリアポインタ",
     "en": "BASIC area pointer"
    }
   },
   "59472": {
    "r": [],
    "w": [
     "L5ACA"
    ]
   },
   "60092": {
    "r": [],
    "w": [
     "L5ACA"
    ]
   },
   "60093": {
    "r": [
     "L0030",
     "L0C9C",
     "L11D3",
     "L20FC",
     "L28EC",
     "L5ACA"
    ],
    "w": [
     "L2202",
     "L54FC",
     "L5ACA"
    ]
   },
   "60094": {
    "r": [
     "L194C"
    ],
    "w": [
     "L0632",
     "L194C"
    ]
   },
   "60095": {
    "r": [],
    "w": [
     "L0632"
    ]
   },
   "60096": {
    "r": [
     "L0B34",
     "L1BBB"
    ],
    "w": [
     "L1BBB"
    ]
   },
   "60098": {
    "r": [
     "L0A15",
     "L0A8D",
     "L0B0B"
    ],
    "w": [
     "L0B4F",
     "L5441"
    ]
   },
   "60100": {
    "r": [
     "L0A8D",
     "L0B34",
     "L0B4F",
     "L1ABF"
    ],
    "w": []
   },
   "60108": {
    "r": [
     "L4EC1",
     "L4F21"
    ],
    "w": []
   },
   "60110": {
    "r": [
     "L54FC",
     "L56E7"
    ],
    "w": [
     "L4FB4",
     "L50CD",
     "L54FC",
     "L56E7"
    ]
   },
   "60143": {
    "r": [
     "L5680"
    ],
    "w": []
   },
   "60145": {
    "r": [
     "L5572",
     "L56CC"
    ],
    "w": [
     "L4F21",
     "L5572",
     "L56CC",
     "L766B"
    ]
   },
   "60147": {
    "r": [
     "L11D3",
     "L28EC",
     "L2907",
     "L2C50"
    ],
    "w": [
     "L11D3",
     "L294B"
    ]
   },
   "60155": {
    "r": [
     "L5ACA"
    ],
    "w": [
     "L4FB4",
     "L5ACA"
    ]
   },
   "60157": {
    "r": [
     "L4FB4"
    ],
    "w": [
     "L0C9C",
     "L4F21"
    ]
   },
   "60159": {
    "r": [
     "L1BBB",
     "L1C81"
    ],
    "w": [
     "L1BBB"
    ]
   },
   "60160": {
    "r": [
     "L04A7",
     "L5F92",
     "L5FD8"
    ],
    "w": [
     "L04A7"
    ]
   },
   "60161": {
    "r": [
     "L04A7"
    ],
    "w": []
   },
   "60165": {
    "r": [
     "L50FB"
    ],
    "w": [
     "L0996",
     "L50CD"
    ]
   },
   "60167": {
    "r": [
     "L03F3"
    ],
    "w": [
     "L0996",
     "L4EC1",
     "L4F21"
    ]
   },
   "60169": {
    "r": [
     "L0451",
     "L6568"
    ],
    "w": [
     "L03B3"
    ]
   },
   "60173": {
    "r": [],
    "w": [
     "L4F21"
    ]
   },
   "60175": {
    "r": [
     "L0375",
     "L5059"
    ],
    "w": [
     "L4F21"
    ]
   },
   "60176": {
    "r": [
     "L11D3",
     "L2A5A"
    ],
    "w": [
     "L11D3",
     "L2C58",
     "L2C6B"
    ]
   },
   "60178": {
    "r": [],
    "w": [
     "L50FB"
    ]
   },
   "60180": {
    "r": [],
    "w": [
     "L4F21",
     "L50FB"
    ]
   },
   "60182": {
    "r": [
     "L06D0",
     "L0C9C",
     "L4F21",
     "L537D",
     "L585A"
    ],
    "w": []
   },
   "60186": {
    "r": [
     "L53F6",
     "L5441"
    ],
    "w": [
     "L4F21",
     "L53F6"
    ]
   },
   "60187": {
    "r": [
     "L537D",
     "L53D2",
     "L53F6",
     "L5ACA"
    ],
    "w": [
     "L06D0",
     "L4F21",
     "L53D2"
    ]
   },
   "60189": {
    "r": [
     "L5ACA"
    ],
    "w": [
     "L06D0",
     "L4F21",
     "L53F6"
    ]
   },
   "60191": {
    "r": [
     "L5572",
     "L585A"
    ],
    "w": [
     "L06D0",
     "L4F21",
     "L53F6"
    ]
   },
   "60193": {
    "r": [],
    "w": [
     "L50A5"
    ]
   },
   "60221": {
    "r": [],
    "w": [
     "L4FB4"
    ]
   },
   "60223": {
    "r": [
     "L5ACA"
    ],
    "w": [
     "L4FB4"
    ]
   },
   "60327": {
    "r": [],
    "w": [
     "L4FB4"
    ]
   },
   "60429": {
    "r": [
     "L5ACA"
    ],
    "w": [
     "L5ACA"
    ]
   },
   "60430": {
    "r": [
     "L5ACA"
    ],
    "w": [
     "L5ACA"
    ]
   },
   "60431": {
    "r": [
     "L5ACA"
    ],
    "w": []
   },
   "60432": {
    "r": [
     "L5ACA"
    ],
    "w": [
     "L4FB4"
    ]
   },
   "60435": {
    "r": [],
    "w": [
     "L4FB4"
    ]
   },
   "60447": {
    "r": [],
    "w": [
     "L4F21"
    ]
   },
   "60448": {
    "r": [],
    "w": [
     "L4F21"
    ]
   },
   "60449": {
    "r": [
     "L194C"
    ],
    "w": [
     "L194C"
    ]
   },
   "60455": {
    "r": [],
    "w": [
     "L03B3",
     "L4DB5"
    ]
   },
   "60458": {
    "r": [
     "L4F21"
    ],
    "w": []
   },
   "60464": {
    "r": [
     "L4F21"
    ],
    "w": []
   },
   "60475": {
    "r": [
     "L0996"
    ],
    "w": []
   },
   "60476": {
    "r": [
     "L24C2"
    ],
    "w": [
     "L22DD",
     "L2424"
    ]
   },
   "60477": {
    "r": [
     "L2954"
    ],
    "w": [
     "L2954"
    ]
   },
   "60479": {
    "r": [
     "L2954"
    ],
    "w": [
     "L2954"
    ]
   },
   "60481": {
    "r": [
     "L0C9C",
     "L20BD",
     "L20CD",
     "L23F7",
     "L2D0F",
     "L5680",
     "L56CC"
    ],
    "w": [
     "L20DD",
     "L21FD",
     "L2D0F",
     "L54FC"
    ]
   },
   "60483": {
    "r": [
     "L06E3",
     "L2083",
     "L20CD",
     "L22DD",
     "L248C"
    ],
    "w": [
     "L20DD"
    ]
   },
   "60484": {
    "r": [
     "L0028",
     "L1B9D",
     "L1DE9",
     "L2BC8"
    ],
    "w": [
     "L1E4E"
    ]
   },
   "60485": {
    "r": [
     "L283C"
    ],
    "w": []
   },
   "60486": {
    "r": [],
    "w": [
     "L11D3",
     "L1DD4"
    ]
   },
   "60488": {
    "r": [
     "L29F0"
    ],
    "w": [
     "L2954"
    ]
   },
   "60489": {
    "r": [
     "L2424"
    ],
    "w": []
   },
   "60496": {
    "r": [],
    "w": [
     "L268A"
    ]
   },
   "60497": {
    "r": [
     "L2553"
    ],
    "w": []
   },
   "60541": {
    "r": [],
    "w": [],
    "known": {
     "name": "drive_total",
     "ja": "総ドライブ数(drivetab_buildが設定)",
     "en": "total drive count (set by drivetab_build)"
    }
   },
   "60542": {
    "r": [
     "L46F8",
     "L4B0C"
    ],
    "w": []
   },
   "60543": {
    "r": [
     "L46F8"
    ],
    "w": []
   },
   "60549": {
    "r": [],
    "w": [],
    "known": {
     "name": "drive_current",
     "ja": "カレントドライブ",
     "en": "current drive"
    }
   },
   "60552": {
    "r": [
     "L4B54",
     "L4B7B",
     "L4B8C",
     "L5372",
     "L59AC",
     "L661C",
     "L7570"
    ],
    "w": [
     "L0F8B",
     "L4735",
     "L481D",
     "L59AC",
     "L740C",
     "L7497",
     "L75AA"
    ]
   },
   "60558": {
    "r": [
     "L5A08"
    ],
    "w": []
   },
   "60579": {
    "r": [
     "L46F8",
     "L481D",
     "L4B0C",
     "L4F21",
     "L5A08"
    ],
    "w": [
     "L03B3",
     "L4DB5",
     "L4F21",
     "L5A08",
     "L75AA",
     "L75DA"
    ]
   },
   "60580": {
    "r": [],
    "w": [
     "L03B3",
     "L4DB5"
    ]
   },
   "60586": {
    "r": [
     "sub_check_result"
    ],
    "w": []
   },
   "60588": {
    "r": [
     "sub_check_result"
    ],
    "w": []
   },
   "60596": {
    "r": [
     "sub_check_result"
    ],
    "w": [
     "sub_ensure_init",
     "sub_check_result"
    ],
    "known": {
     "name": "boot_retry_ctr",
     "ja": "ディスクブートのリトライカウンタ(最大4)",
     "en": "disk boot retry counter (max 4)"
    }
   },
   "60598": {
    "r": [
     "sub_check_result"
    ],
    "w": []
   },
   "61194": {
    "r": [
     "veccall_enter",
     "veccall_restore_a71"
    ],
    "w": [
     "veccall_enter",
     "veccall_restore_a71"
    ]
   },
   "61195": {
    "r": [
     "veccall_enter"
    ],
    "w": [
     "veccall_enter"
    ]
   },
   "61198": {
    "r": [
     "L4250",
     "L7DA6"
    ],
    "w": [
     "L424A",
     "coldstart_block",
     "L7DA6"
    ]
   },
   "61199": {
    "r": [],
    "w": [
     "L38E9",
     "L3AED"
    ]
   },
   "61200": {
    "r": [
     "sub_hs_timeout"
    ],
    "w": [
     "coldstart_block"
    ],
    "known": {
     "name": "sub_hs_bailmode",
     "ja": "ハンドシェイクタイムアウト時の脱出先選択",
     "en": "handshake-timeout bail-out selector"
    }
   },
   "61201": {
    "r": [],
    "w": [
     "L38E9"
    ]
   },
   "61204": {
    "r": [
     "L37D2"
    ],
    "w": [
     "sub_ensure_init",
     "sub_init_and_count"
    ],
    "known": {
     "name": "sub_hs_timeout_d",
     "ja": "ハンドシェイクタイムアウトのD初期値(BC×D)",
     "en": "handshake timeout D reload (BC×D spins)"
    }
   },
   "61205": {
    "r": [],
    "w": [
     "L3DE9"
    ]
   },
   "61206": {
    "r": [],
    "w": [
     "L3975"
    ]
   },
   "61207": {
    "r": [
     "L3975"
    ],
    "w": [
     "L38E9"
    ]
   },
   "61214": {
    "r": [
     "L3975"
    ],
    "w": []
   },
   "61216": {
    "r": [
     "L3975"
    ],
    "w": [
     "L3975"
    ]
   },
   "61245": {
    "r": [
     "L38E9"
    ],
    "w": []
   },
   "61258": {
    "r": [
     "sub_send_rw_cmd"
    ],
    "w": [],
    "known": {
     "name": "sub_rw_unit",
     "ja": "サブR/Wコマンドのユニット番号",
     "en": "unit number for sub R/W commands"
    }
   },
   "61259": {
    "r": [
     "L38E9"
    ],
    "w": []
   },
   "61277": {
    "r": [
     "sub_recv_data",
     "sub_send_data",
     "L3975",
     "L3DE9"
    ],
    "w": [
     "coldstart_block"
    ],
    "known": {
     "name": "sub_rw_iface",
     "ja": "インターフェース種別(EF64から転記、2=密結合)",
     "en": "interface type (copied from EF64; 2 = packed)"
    }
   },
   "61279": {
    "r": [
     "sub_send_rw_cmd"
    ],
    "w": [],
    "known": {
     "name": "sub_rw_track",
     "ja": "サブR/Wコマンドのトラック",
     "en": "track for sub R/W commands"
    }
   },
   "61280": {
    "r": [],
    "w": [],
    "known": {
     "name": "drives_int_a",
     "ja": "内蔵I/F Aのドライブ数(EF35表から)",
     "en": "internal i/f A drive count (from EF35 table)"
    }
   },
   "61281": {
    "r": [],
    "w": [],
    "known": {
     "name": "drives_int_b",
     "ja": "内蔵I/F Bのドライブ数(EF2D表から)",
     "en": "internal i/f B drive count (from EF2D table)"
    }
   },
   "61282": {
    "r": [],
    "w": [
     "sub_hs_timeout",
     "coldstart_block"
    ],
    "known": {
     "name": "drives_sub",
     "ja": "サブシステムのドライブ数(cmd 07の答えから)",
     "en": "sub-system drive count (from the cmd 07 answer)"
    }
   },
   "61283": {
    "r": [],
    "w": [],
    "known": {
     "name": "sub_features",
     "ja": "サブ機能フラグ(cmd 0Bの答えのCPL&F0)",
     "en": "sub feature flags (CPL&F0 of the cmd 0B answer)"
    }
   },
   "61284": {
    "r": [],
    "w": [],
    "known": {
     "name": "drive_iface_tab",
     "ja": "ドライブ→インターフェース対応表(EF64-)",
     "en": "drive → interface table (EF64-)"
    }
   },
   "61297": {
    "r": [
     "L740C"
    ],
    "w": []
   },
   "61298": {
    "r": [
     "L740C"
    ],
    "w": []
   },
   "61299": {
    "r": [
     "L7497"
    ],
    "w": []
   },
   "61302": {
    "r": [
     "L766B"
    ],
    "w": []
   },
   "61304": {
    "r": [
     "L76D3",
     "L776C"
    ],
    "w": []
   },
   "61306": {
    "r": [
     "L76D3",
     "L776C"
    ],
    "w": []
   },
   "61308": {
    "r": [
     "L7716",
     "L777A"
    ],
    "w": []
   },
   "61310": {
    "r": [
     "L7716"
    ],
    "w": []
   },
   "61311": {
    "r": [
     "L69E1",
     "boot_stop_key_fork"
    ],
    "w": [
     "L77F7"
    ],
    "known": {
     "name": "dipsw_cpl",
     "ja": "DIP SW反転シャドウ(~30h | ~31h<<8)",
     "en": "inverted DIP shadow (~30h | ~31h<<8)"
    }
   },
   "61315": {
    "r": [
     "L5FD8"
    ],
    "w": [
     "L5E49",
     "L5F0E",
     "L5F92",
     "L5FC8",
     "L5FD8"
    ]
   },
   "61316": {
    "r": [],
    "w": [
     "L5F0E"
    ]
   },
   "61317": {
    "r": [
     "L5FD8"
    ],
    "w": [
     "L5F0E",
     "L5FD8"
    ]
   },
   "61318": {
    "r": [
     "L1933",
     "L5F92",
     "L5FC8",
     "L5FD8",
     "L605B",
     "L6568",
     "L6FB4",
     "L7403",
     "L7583"
    ],
    "w": [
     "L4494",
     "L6FB4",
     "L7583"
    ]
   },
   "61319": {
    "r": [
     "L449F"
    ],
    "w": []
   },
   "61320": {
    "r": [
     "L4021"
    ],
    "w": [
     "L6F6A"
    ]
   },
   "61321": {
    "r": [
     "L3F79",
     "L429D",
     "L4350",
     "L5FBC",
     "L6347",
     "L6528",
     "L7747"
    ],
    "w": [
     "L6F6A"
    ]
   },
   "61322": {
    "r": [],
    "w": [
     "L4422"
    ]
   },
   "61324": {
    "r": [
     "L4350"
    ],
    "w": [
     "L4350"
    ]
   },
   "61325": {
    "r": [
     "L4350"
    ],
    "w": [
     "L4422"
    ]
   },
   "61326": {
    "r": [
     "L4350"
    ],
    "w": [
     "L4350"
    ]
   },
   "61328": {
    "r": [
     "L3F79"
    ],
    "w": [
     "L3F79"
    ]
   },
   "61364": {
    "r": [],
    "w": [
     "L5F0E",
     "L6568"
    ]
   },
   "61365": {
    "r": [
     "L0605"
    ],
    "w": [
     "L0605",
     "L44E3"
    ]
   },
   "61367": {
    "r": [],
    "w": [
     "L0605"
    ]
   },
   "61369": {
    "r": [
     "L5F92"
    ],
    "w": [
     "L5FD8",
     "L6568"
    ]
   },
   "61370": {
    "r": [
     "L03B3",
     "L50CD"
    ],
    "w": [
     "L0A0D"
    ]
   },
   "61372": {
    "r": [
     "L194C"
    ],
    "w": [
     "L03B3",
     "L50CD",
     "L6568"
    ]
   },
   "61373": {
    "r": [
     "L6568"
    ],
    "w": [
     "L6568"
    ]
   },
   "61374": {
    "r": [],
    "w": [
     "L03B3",
     "L50CD",
     "L6568"
    ]
   },
   "61376": {
    "r": [
     "L1933"
    ],
    "w": [
     "L194C",
     "L6568"
    ]
   },
   "61378": {
    "r": [
     "L6568"
    ],
    "w": [
     "L1933",
     "L6568"
    ]
   },
   "61443": {
    "r": [
     "L34EA"
    ],
    "w": [
     "L34D8",
     "L34FC"
    ]
   },
   "61446": {
    "r": [],
    "w": [
     "L03B3"
    ]
   },
   "61447": {
    "r": [],
    "w": [
     "L03B3"
    ]
   },
   "61458": {
    "r": [],
    "w": [
     "coldstart_block"
    ]
   },
   "61648": {
    "r": [],
    "w": [
     "L77AB"
    ]
   },
   "61649": {
    "r": [],
    "w": [
     "L77AB"
    ]
   }
  }
 },
 "pc80s31": {
  "routines": {
   "0": {
    "name": "(entry)",
    "calls": [
     126
    ],
    "callers": [],
    "size": 3
   },
   "16": {
    "name": "L0010",
    "calls": [
     1753
    ],
    "callers": [
     "cmd_dispatch",
     "cmd17_mode_flags",
     "recv_params_bcde"
    ],
    "size": 3
   },
   "32": {
    "name": "L0020",
    "calls": [
     679
    ],
    "callers": [
     "cmd00_initialize",
     "L0196",
     "L01AA",
     "L0205"
    ],
    "size": 3
   },
   "126": {
    "name": "L007E",
    "calls": [
     859
    ],
    "callers": [
     "(entry)"
    ],
    "size": 51
   },
   "177": {
    "name": "poweron_pio_init",
    "calls": [],
    "callers": [],
    "size": 16
   },
   "193": {
    "name": "L00C1",
    "calls": [],
    "callers": [
     "L06D9",
     "send_byte_to_main"
    ],
    "size": 11
   },
   "204": {
    "name": "idle_poll_loop",
    "calls": [
     406
    ],
    "callers": [],
    "size": 24
   },
   "236": {
    "name": "cmd_dispatch",
    "calls": [
     16,
     692
    ],
    "callers": [],
    "size": 47
   },
   "283": {
    "name": "cmd_jump_table",
    "calls": [
     54533,
     517
    ],
    "callers": [],
    "size": 66
   },
   "349": {
    "name": "cmd00_initialize",
    "calls": [
     32,
     406,
     426
    ],
    "callers": [],
    "size": 57
   },
   "406": {
    "name": "L0196",
    "calls": [
     676,
     32,
     460
    ],
    "callers": [
     "idle_poll_loop",
     "cmd00_initialize",
     "L01AA"
    ],
    "size": 20
   },
   "426": {
    "name": "L01AA",
    "calls": [
     1737,
     676,
     32,
     1051,
     460,
     406
    ],
    "callers": [
     "cmd00_initialize"
    ],
    "size": 34
   },
   "460": {
    "name": "L01CC",
    "calls": [],
    "callers": [
     "L0196",
     "L01AA"
    ],
    "size": 2
   },
   "517": {
    "name": "L0205",
    "calls": [
     1051,
     32
    ],
    "callers": [
     "cmd_jump_table"
    ],
    "size": 21
   },
   "676": {
    "name": "fdc_send_cmd",
    "calls": [],
    "callers": [
     "L0196",
     "L01AA"
    ],
    "size": 3
   },
   "679": {
    "name": "L02A7",
    "calls": [],
    "callers": [
     "L0020"
    ],
    "size": 13
   },
   "692": {
    "name": "motor_settle_delay",
    "calls": [
     695
    ],
    "callers": [
     "cmd_dispatch"
    ],
    "size": 3
   },
   "695": {
    "name": "L02B7",
    "calls": [],
    "callers": [
     "motor_settle_delay"
    ],
    "size": 11
   },
   "859": {
    "name": "L035B",
    "calls": [
     1282
    ],
    "callers": [
     "L007E"
    ],
    "size": 19
   },
   "1051": {
    "name": "L041B",
    "calls": [
     1059
    ],
    "callers": [
     "L01AA",
     "L0205",
     "L06C9"
    ],
    "size": 8
   },
   "1059": {
    "name": "L0423",
    "calls": [],
    "callers": [
     "L041B"
    ],
    "size": 12
   },
   "1282": {
    "name": "L0502",
    "calls": [],
    "callers": [
     "L035B"
    ],
    "size": 9
   },
   "1468": {
    "name": "cmd17_mode_flags",
    "calls": [
     16
    ],
    "callers": [],
    "size": 18
   },
   "1498": {
    "name": "cmd1b_remote_exec",
    "calls": [
     32549
    ],
    "callers": [],
    "size": 40
   },
   "1702": {
    "name": "recv_params_bcde",
    "calls": [
     16
    ],
    "callers": [],
    "size": 9
   },
   "1737": {
    "name": "L06C9",
    "calls": [
     1051
    ],
    "callers": [
     "L01AA"
    ],
    "size": 16
   },
   "1753": {
    "name": "L06D9",
    "calls": [
     193
    ],
    "callers": [
     "L0010"
    ],
    "size": 24
   },
   "1807": {
    "name": "send_byte_to_main",
    "calls": [
     193
    ],
    "callers": [],
    "size": 14
   }
  },
  "vars": {
   "32512": {
    "r": [],
    "w": [
     "L007E"
    ]
   },
   "32514": {
    "r": [],
    "w": [
     "L007E"
    ]
   },
   "32516": {
    "r": [],
    "w": [
     "L007E"
    ]
   },
   "32518": {
    "r": [],
    "w": [
     "L007E"
    ]
   },
   "32521": {
    "r": [
     "cmd_dispatch"
    ],
    "w": [
     "poweron_pio_init",
     "idle_poll_loop",
     "cmd_dispatch"
    ],
    "known": {
     "name": "motors_spun",
     "ja": "モーター安定済みフラグ(FFで02B4の1.7秒待ちをスキップ)",
     "en": "motors-spun flag (FF skips the 1.7s settle at 02B4)"
    }
   },
   "32524": {
    "r": [],
    "w": [
     "fdc_send_cmd"
    ],
    "known": {
     "name": "fdc_last_cmd",
     "ja": "最後にFDCへ送ったコマンド",
     "en": "last command sent to the FDC"
    }
   },
   "32532": {
    "r": [
     "L0502"
    ],
    "w": [
     "cmd00_initialize",
     "L0502"
    ],
    "known": {
     "name": "result_status",
     "ja": "cmd 06で返す結果ステータス(init直後=80h)",
     "en": "result status served by cmd 06 (80h right after init)"
    }
   },
   "32533": {
    "r": [
     "cmd00_initialize"
    ],
    "w": [
     "cmd00_initialize"
    ],
    "known": {
     "name": "drive_map",
     "ja": "cmd 07で返すドライブマップ(RRAで詰めたプローブ結果)",
     "en": "drive map served by cmd 07 (probe carries packed via RRA)"
    }
   },
   "32534": {
    "r": [
     "L06D9"
    ],
    "w": [
     "cmd_dispatch"
    ]
   },
   "32535": {
    "r": [],
    "w": [
     "L007E"
    ]
   },
   "32536": {
    "r": [],
    "w": [
     "L007E"
    ]
   },
   "32539": {
    "r": [],
    "w": [
     "cmd17_mode_flags"
    ]
   },
   "32540": {
    "r": [],
    "w": [],
    "known": {
     "name": "mode_flags",
     "ja": "cmd 17のドライブ別モードフラグ(7F1C-1F)",
     "en": "per-drive mode flags from cmd 17 (7F1C-1F)"
    }
   },
   "32544": {
    "r": [],
    "w": [
     "L007E"
    ]
   },
   "32546": {
    "r": [],
    "w": [
     "L007E"
    ]
   },
   "32549": {
    "r": [],
    "w": [
     "cmd1b_remote_exec"
    ],
    "known": {
     "name": "remote_entry",
     "ja": "cmd 1Bリモート実行のエントリ(JP先が書かれる)",
     "en": "cmd 1B remote-exec entry (a JP lands here)"
    }
   },
   "32550": {
    "r": [],
    "w": [
     "cmd1b_remote_exec"
    ]
   },
   "32552": {
    "r": [
     "cmd1b_remote_exec"
    ],
    "w": []
   },
   "32554": {
    "r": [
     "cmd1b_remote_exec"
    ],
    "w": []
   },
   "32556": {
    "r": [
     "cmd1b_remote_exec"
    ],
    "w": []
   },
   "32578": {
    "r": [],
    "w": [
     "L007E"
    ]
   }
  }
 }
};

// who writes this address? (names of routines)
export function writersOf(setName, addr) {
  return ROM_XREF[setName]?.vars?.[addr]?.w ?? [];
}
export function readersOf(setName, addr) {
  return ROM_XREF[setName]?.vars?.[addr]?.r ?? [];
}
