// snap — deep-copy helpers for machine snapshots.
//
// Everything in this repo keeps its state in plain fields: numbers, bools,
// typed arrays, small plain objects. That discipline (no hidden closures
// holding state) is what makes time travel cheap: copy the fields out,
// copy them back in, and a deterministic machine lands on the exact same
// timeline. Functions are skipped on the way out and preserved on the way
// in — wiring (DRQ hooks, cross-wired 8255 reads) belongs to the board,
// not to the snapshot.
//
// Pure, dependency-free. Not a general serializer: no cycles, no Maps
// (callers handle those), no class reconstruction — restore() writes into
// EXISTING objects.

export const SCHEMA_VERSION = 1;

const isTyped = (v) => ArrayBuffer.isView(v) && !(v instanceof DataView);

// Copy the own enumerable state of `obj` into a plain object.
export function snapObj(obj) {
  const out = {};
  for (const k of Object.keys(obj)) {
    const v = obj[k];
    if (typeof v === 'function' || v === undefined) continue;
    out[k] = snapValue(v);
  }
  return out;
}

function snapValue(v) {
  if (v === null || typeof v !== 'object') return v;
  if (isTyped(v)) return v.slice();
  if (Array.isArray(v)) return v.map(snapValue);
  return snapObj(v);
}

// Write a snapshot back into an existing object. Typed arrays are copied
// in place when the length matches (keeps views/aliases alive); plain
// objects recurse; anything else is assigned.
export function restoreObj(obj, snap) {
  for (const k of Object.keys(snap)) {
    const v = snap[k];
    const cur = obj[k];
    if (isTyped(v)) {
      if (isTyped(cur) && cur.length === v.length) cur.set(v);
      else obj[k] = v.slice();
    } else if (Array.isArray(v)) {
      obj[k] = v.map(snapValue);
    } else if (v !== null && typeof v === 'object') {
      if (cur !== null && typeof cur === 'object' && !Array.isArray(cur) && !isTyped(cur)) {
        restoreObj(cur, v);
      } else {
        obj[k] = snapValue(v);
      }
    } else {
      obj[k] = v;
    }
  }
  return obj;
}

// ---- pictures --------------------------------------------------------------
//
// A frame buffer belongs in the snapshot. That is not obvious — it looks like
// output, it is regenerated by the next frame, and three of the machines in
// this repository said so in a comment and left it out. It is wrong anyway:
// the host restores a snapshot and DRAWS it without stepping a frame (see
// demo/machine.html's restoreIdx), so a snapshot with no picture in it hands
// back whatever was on screen last, and every slot of the rewind ring shows
// the newest frame. The Game Boy found this on 2026-08-10; the NES and the PC
// Engine had it too.
//
// It is also the biggest single thing in a snapshot, so it goes in packed.
// These buffers carry 6 or 9 significant bits per pixel in an 8- or 16-bit
// array — a 2C02 frame is 61,440 six-bit palette indices, which is 46,080
// bytes instead of 61,440 — and a plane that is constant for whole frames
// (colour emphasis, mode bits) compresses to a handful of bytes as runs.
//
// Both directions are exact. A picture is not something to approximate: the
// point of storing it is that a restored frame is the frame that was captured.

/** Pack `len` values of `bits` significant bits each, MSB first. bits ≤ 16. */
export function packPixels(src, bits, len = src.length) {
  const mask = (1 << bits) - 1;
  const out = new Uint8Array((len * bits + 7) >> 3);
  let acc = 0, n = 0, o = 0;
  for (let i = 0; i < len; i++) {
    acc = (acc << bits) | (src[i] & mask);
    n += bits;
    while (n >= 8) { n -= 8; out[o++] = (acc >>> n) & 0xff; acc &= (1 << n) - 1; }
  }
  if (n) out[o] = (acc << (8 - n)) & 0xff;
  return out;
}

/** The inverse. Writes into `out` when given one, so a restore keeps the
 *  machine's existing buffer (and every view onto it) alive. */
export function unpackPixels(packed, bits, len, out = null) {
  const dst = out ?? new Uint16Array(len);
  const mask = (1 << bits) - 1;
  let acc = 0, n = 0, o = 0;
  for (let i = 0; i < len; i++) {
    while (n < bits) { acc = (acc << 8) | (o < packed.length ? packed[o++] : 0); n += 8; }
    n -= bits;
    dst[i] = (acc >>> n) & mask;
    acc &= (1 << n) - 1;
  }
  return dst;
}

/** Run-length encode a byte plane as (count, value) pairs. For planes that are
 *  usually one value for the whole frame; worst case is 4x, which is why this
 *  is only used on planes that are known to be flat. */
export function rlePlane(src) {
  const out = [];
  for (let i = 0; i < src.length;) {
    const v = src[i] & 0xff;
    let n = 1;
    while (i + n < src.length && (src[i + n] & 0xff) === v && n < 0xffff) n++;
    out.push(n, v);
    i += n;
  }
  return Uint16Array.from(out);
}

export function unrlePlane(rle, len, out = null) {
  const dst = out ?? new Uint8Array(len);
  let o = 0;
  for (let i = 0; i + 1 < rle.length && o < len; i += 2) {
    const n = Math.min(rle[i], len - o);
    dst.fill(rle[i + 1] & 0xff, o, o + n);
    o += n;
  }
  if (o < len) dst.fill(0, o, len);
  return dst;
}
