from collections import defaultdict
from skidl import Pin, Part, Alias, SchLib, SKIDL, TEMPLATE

from skidl.pin import pin_types

SKIDL_lib_version = '0.0.1'

make_pcb = SchLib(tool=SKIDL).add_parts(*[
        Part(**{ 'name':'PC8001_EXPANSION', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'PC8001_EXPANSION'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Connector_PinSocket_2.54mm:PinSocket_2x25_P2.54mm_Vertical', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',name='+5V',func=pin_types.PWRIN),
            Pin(num='2',name='GND',func=pin_types.PWRIN),
            Pin(num='50',name='GND2',func=pin_types.PWRIN),
            Pin(num='3',name='D0',func=pin_types.BIDIR),
            Pin(num='4',name='D1',func=pin_types.BIDIR),
            Pin(num='5',name='D2',func=pin_types.BIDIR),
            Pin(num='6',name='D3',func=pin_types.BIDIR),
            Pin(num='7',name='D4',func=pin_types.BIDIR),
            Pin(num='8',name='D5',func=pin_types.BIDIR),
            Pin(num='9',name='D6',func=pin_types.BIDIR),
            Pin(num='10',name='D7',func=pin_types.BIDIR),
            Pin(num='11',name='A0',func=pin_types.INPUT),
            Pin(num='12',name='A1',func=pin_types.INPUT),
            Pin(num='13',name='A2',func=pin_types.INPUT),
            Pin(num='14',name='A3',func=pin_types.INPUT),
            Pin(num='15',name='A4',func=pin_types.INPUT),
            Pin(num='16',name='A5',func=pin_types.INPUT),
            Pin(num='17',name='A6',func=pin_types.INPUT),
            Pin(num='18',name='A7',func=pin_types.INPUT),
            Pin(num='19',name='~IORQ',func=pin_types.INPUT),
            Pin(num='20',name='~RD',func=pin_types.INPUT),
            Pin(num='21',name='~M1',func=pin_types.INPUT),
            Pin(num='22',name='~RESET',func=pin_types.INPUT),
            Pin(num='23',name='~WAIT',func=pin_types.OPENCOLL)] }),
        Part(**{ 'name':'RPi_Pico', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'RPi_Pico'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'vstream:RPi_Pico_TH', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='39',name='VSYS',func=pin_types.PWRIN),
            Pin(num='36',name='3V3_OUT',func=pin_types.PWRIN),
            Pin(num='38',name='GND',func=pin_types.PWRIN),
            Pin(num='3',name='GND2',func=pin_types.PWRIN),
            Pin(num='1',name='GP0',func=pin_types.BIDIR),
            Pin(num='2',name='GP1',func=pin_types.BIDIR),
            Pin(num='3',name='GP2',func=pin_types.BIDIR),
            Pin(num='5',name='GP3',func=pin_types.BIDIR),
            Pin(num='6',name='GP4',func=pin_types.BIDIR),
            Pin(num='7',name='GP5',func=pin_types.BIDIR),
            Pin(num='8',name='GP6',func=pin_types.BIDIR),
            Pin(num='9',name='GP7',func=pin_types.BIDIR),
            Pin(num='11',name='GP8',func=pin_types.INPUT),
            Pin(num='12',name='GP9',func=pin_types.OUTPUT),
            Pin(num='14',name='GP10',func=pin_types.INPUT),
            Pin(num='21',name='GP16',func=pin_types.INPUT),
            Pin(num='22',name='GP17',func=pin_types.OUTPUT),
            Pin(num='24',name='GP18',func=pin_types.OUTPUT),
            Pin(num='25',name='GP19',func=pin_types.OUTPUT)] }),
        Part(**{ 'name':'74LVC245A', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'74LVC245A'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Package_SO:TSSOP-20_4.4x6.5mm_P0.65mm', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',name='DIR',func=pin_types.INPUT),
            Pin(num='19',name='~OE',func=pin_types.INPUT),
            Pin(num='20',name='VCC',func=pin_types.PWRIN),
            Pin(num='10',name='GND',func=pin_types.PWRIN),
            Pin(num='2',name='A0',func=pin_types.BIDIR),
            Pin(num='3',name='A1',func=pin_types.BIDIR),
            Pin(num='4',name='A2',func=pin_types.BIDIR),
            Pin(num='5',name='A3',func=pin_types.BIDIR),
            Pin(num='6',name='A4',func=pin_types.BIDIR),
            Pin(num='7',name='A5',func=pin_types.BIDIR),
            Pin(num='8',name='A6',func=pin_types.BIDIR),
            Pin(num='9',name='A7',func=pin_types.BIDIR),
            Pin(num='18',name='B0',func=pin_types.BIDIR),
            Pin(num='17',name='B1',func=pin_types.BIDIR),
            Pin(num='16',name='B2',func=pin_types.BIDIR),
            Pin(num='15',name='B3',func=pin_types.BIDIR),
            Pin(num='14',name='B4',func=pin_types.BIDIR),
            Pin(num='13',name='B5',func=pin_types.BIDIR),
            Pin(num='12',name='B6',func=pin_types.BIDIR),
            Pin(num='11',name='B7',func=pin_types.BIDIR)] }),
        Part(**{ 'name':'74HC688', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'74HC688'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Package_SO:SOIC-20W_7.5x12.8mm_P1.27mm', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='20',name='VCC',func=pin_types.PWRIN),
            Pin(num='10',name='GND',func=pin_types.PWRIN),
            Pin(num='1',name='~G',func=pin_types.INPUT),
            Pin(num='19',name='~P=Q',func=pin_types.OUTPUT),
            Pin(num='2',name='P0',func=pin_types.INPUT),
            Pin(num='4',name='P1',func=pin_types.INPUT),
            Pin(num='6',name='P2',func=pin_types.INPUT),
            Pin(num='8',name='P3',func=pin_types.INPUT),
            Pin(num='10',name='P4',func=pin_types.INPUT),
            Pin(num='12',name='P5',func=pin_types.INPUT),
            Pin(num='14',name='P6',func=pin_types.INPUT),
            Pin(num='16',name='P7',func=pin_types.INPUT),
            Pin(num='3',name='Q0',func=pin_types.INPUT),
            Pin(num='5',name='Q1',func=pin_types.INPUT),
            Pin(num='7',name='Q2',func=pin_types.INPUT),
            Pin(num='9',name='Q3',func=pin_types.INPUT),
            Pin(num='11',name='Q4',func=pin_types.INPUT),
            Pin(num='13',name='Q5',func=pin_types.INPUT),
            Pin(num='15',name='Q6',func=pin_types.INPUT),
            Pin(num='17',name='Q7',func=pin_types.INPUT)] }),
        Part(**{ 'name':'74HC32', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'74HC32'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Package_SO:SOIC-14_3.9x8.7mm_P1.27mm', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='14',name='VCC',func=pin_types.PWRIN),
            Pin(num='7',name='GND',func=pin_types.PWRIN),
            Pin(num='1',name='1A',func=pin_types.INPUT),
            Pin(num='2',name='1B',func=pin_types.INPUT),
            Pin(num='3',name='1Y',func=pin_types.OUTPUT),
            Pin(num='4',name='2A',func=pin_types.INPUT),
            Pin(num='5',name='2B',func=pin_types.INPUT),
            Pin(num='6',name='2Y',func=pin_types.OUTPUT),
            Pin(num='9',name='3A',func=pin_types.INPUT),
            Pin(num='10',name='3B',func=pin_types.INPUT),
            Pin(num='8',name='3Y',func=pin_types.OUTPUT)] }),
        Part(**{ 'name':'2N7002', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'2N7002'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Package_TO_SOT_SMD:SOT-23', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',name='G',func=pin_types.INPUT),
            Pin(num='2',name='S',func=pin_types.PWRIN),
            Pin(num='3',name='D',func=pin_types.OPENCOLL)] }),
        Part(**{ 'name':'R_4k7', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'R_4k7'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Resistor_SMD:R_0805_2012Metric', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',name='A',func=pin_types.PWRIN),
            Pin(num='2',name='B',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'R_10k', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'R_10k'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Resistor_SMD:R_0805_2012Metric', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',name='A',func=pin_types.PWRIN),
            Pin(num='2',name='B',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'microSD_SPI', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'microSD_SPI'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Connector_Card:microSD_HC_Hirose_DM3AT-SF-PEJM5', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',name='CS',func=pin_types.INPUT),
            Pin(num='2',name='MOSI',func=pin_types.INPUT),
            Pin(num='3',name='GND',func=pin_types.PWRIN),
            Pin(num='4',name='VDD',func=pin_types.PWRIN),
            Pin(num='5',name='SCK',func=pin_types.INPUT),
            Pin(num='6',name='GND2',func=pin_types.PWRIN),
            Pin(num='7',name='MISO',func=pin_types.OUTPUT)] }),
        Part(**{ 'name':'C_100n', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'C_100n'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Capacitor_SMD:C_0603_1608Metric', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',name='P',func=pin_types.PWRIN),
            Pin(num='2',name='N',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'C_10u', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'C_10u'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Capacitor_SMD:C_0805_2012Metric', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',name='P',func=pin_types.PWRIN),
            Pin(num='2',name='N',func=pin_types.PWRIN)] })])