// gen-romxref — the static complement of the ICE's runtime call stack.
//
// A call stack only exists while the machine runs; this generates the map
// that exists always: for each ROM, (a) the CALL HIERARCHY (who calls whom,
// discovered to a fixpoint — every call target becomes a routine boundary
// and gets re-analyzed), and (b) the WORK-VARIABLE CROSS-REFERENCE (for
// every immediate-addressed RAM byte: which routines read it, which write
// it), joined with the hand-curated names in memmap.WORK_VARS.
//
// usage: node tools/gen-romxref.mjs   (needs BYO ROMs in roms/)
// output: romxref.js (committed — our analysis, not the ROM)
import { readFile, writeFile } from 'node:fs/promises';
import { analyze } from '../z80anal.js';
import { ROM_LABELS } from '../romlabels.js';
import { WORK_VARS } from '../memmap.js';

const load = async (p) => new Uint8Array(await readFile(new URL(`../${p}`, import.meta.url)));

// analyze with fixpoint expansion: every discovered call target inside the
// image becomes a routine boundary for the next round, until nothing new.
function analyzeFixpoint(bytes, org, seedSymbols, ports, maxIter = 12) {
  const symbols = { ...seedSymbols };
  let routines = [];
  for (let i = 0; i < maxIter; i++) {
    ({ routines } = analyze(bytes, org, symbols, { ports }));
    let grew = false;
    for (const r of routines) {
      for (const c of r.calls) {
        if (c.addr < org || c.addr >= org + bytes.length) continue;
        const name = `L${c.addr.toString(16).toUpperCase().padStart(4, '0')}`;
        if (!(name in symbols) && !Object.values(symbols).includes(c.addr)) {
          symbols[name] = c.addr;
          grew = true;
        }
      }
    }
    if (!grew) break;
  }
  return routines;
}

function harvest(bytes, org, labels, ports, ramLo, ramHi, vars) {
  const seed = {};
  for (const l of labels) seed[l.name] = l.addr;
  const routines = analyzeFixpoint(bytes, org, seed, ports);

  const hierarchy = {};
  const varsOut = {};
  for (const r of routines) {
    hierarchy[r.addr] = {
      name: r.name,
      calls: r.calls.map((c) => c.addr),
      callers: r.callers,
      size: r.size,
    };
    for (const mref of r.mem) {
      if (mref.addr === null || mref.addr < ramLo || mref.addr > ramHi) continue;
      const v = (varsOut[mref.addr] ??= { r: [], w: [] });
      const list = mref.rw === 'w' ? v.w : v.r;
      if (!list.includes(r.name)) list.push(r.name);
    }
  }
  // join the hand-curated names
  for (const [addr, info] of Object.entries(vars ?? {})) {
    const a = Number(addr);
    (varsOut[a] ??= { r: [], w: [] }).known = info;
  }
  return { routines: hierarchy, vars: varsOut };
}

const out = {};
try {
  const n88 = await load('roms/8801mkIIFR/n88.rom');
  const set = ROM_LABELS['n88-fr'].labels.filter((l) => ![0x754f, 0x75a1].includes(l.addr));
  out['n88-fr'] = harvest(n88, 0x0000, set, 'pc88-main', 0x8000, 0xffff, WORK_VARS.pc8801);
} catch (e) { console.error('n88 skipped:', e.message); }

try {
  const sub = await load('roms/8801mkIIFR/disk.rom');
  out.pc80s31 = harvest(sub, 0x0000, ROM_LABELS.pc80s31.labels, 'pc88-sub', 0x4000, 0x7fff, WORK_VARS.pc80s31);
} catch (e) { console.error('pc80s31 skipped:', e.message); }

const body = `// GENERATED by tools/gen-romxref.mjs — do not edit by hand.
//
// Static call hierarchy + work-variable cross-reference for the labeled
// ROMs, discovered to a fixpoint (every call target becomes a routine).
// Unlabeled routines carry auto names (L####). Same honesty rules as
// romlabels-meta.js: linear sweeps, no guessing past indirect flow.
// This file contains our analysis of the ROMs, not the ROMs.

export const SCHEMA_VERSION = 1;

export const ROM_XREF = ${JSON.stringify(out, null, 1)};

// who writes this address? (names of routines)
export function writersOf(setName, addr) {
  return ROM_XREF[setName]?.vars?.[addr]?.w ?? [];
}
export function readersOf(setName, addr) {
  return ROM_XREF[setName]?.vars?.[addr]?.r ?? [];
}
`;
await writeFile(new URL('../romxref.js', import.meta.url), body);
for (const [k, v] of Object.entries(out)) {
  console.log(`${k}: ${Object.keys(v.routines).length} routines, ${Object.keys(v.vars).length} RAM vars`);
}
